### ISSUE TITLE
Blog posts not indexed/displayed by author

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#10]
There should be an index of blog posts by author (and the `author` field in posts should be modified to be a list of names to facilitate this).

**Comment by djacquel** [comment]
Hi,
A good solution can be to use [Jekyll collection](http://jekyllrb.com/docs/collections/) to manage authors.

An authors file can look like this (_authors/bradford-twist.md or html) :

```
---
firstName: Bradford
lastName: Twist
slug: bradford-twist
---
<h1>Free html</h1>
or 
#Mardown
```

Post authors are then filled in post with author.slug

```
---
title: my title
authors: [bradford-twist, chan-peckham]
or
authors: 
  - bradford-twist
  - chan-peckham
---
```

A simple loop can then generate the authors with posts list

```
{% for a in site.authors %}
    <h3><a href="{{ site.baseurl }}{{ a.url }}">{{ a.firstName }} {{ a.lastName }}</a></h3>
    {% assign authorPosts = "" | split: "/" %}
    {% for p in site.posts %}
        {% if p.authors contains a.slug %}
            {% assign authorPosts = authorPosts | push: p %}
        {% endif %}
    {% endfor %}
    {% assign authorPostsLength = authorPosts | size %}
    {% if authorPostsLength > 0 %}
        <ul>
        {% for p in authorPosts %}
            <li><a href="{{ site.baseurl }}{{ p.url }}">{{ p.title }}</a></li>
        {% endfor %}
        </ul>
    {% endif %}
{% endfor %}
```

I've just pushed it on github http://pygmeeweb.com/jekyllBoilerplate/authors/
Repository : https://github.com/djacquel/jekyllBoilerplate

It can also be interesting to have _includes/orgs and projects as collections. It will be easiest to play with datas crossing.

**Comment by gvwilson** [comment]
Cool - can it be done using author names as strings, rather than 
creating a separate authors file?

**Comment by djacquel** [comment]
I don't understand your question Greg.

**Comment by gvwilson** [comment]
Sorry, typed it before having tea :-)  Will your technique work if we represent author lists as:

```
author: ["Greg Wilson", "David Jacquel"]
```

rather than using an authors' file and author IDs in the blog posts?  But on reflection, we can do the author IDs, and probably should - we already have IDs for all the authors (see _includes/people/*.html). I'll get a PR with your idea in it if you can focus on the mobile problems (which I'm singularly unqualified to tackle).

**Comment by gvwilson** [comment]
Hm. OK, I like this, but we should combine it with @andreabedini 's idea of moving information about people from _includes/people into _data, since (almost) all of the authors will also be instructors. Where should the data go? In a new top-level directory _people? Under _data/people? Or...?

**Comment by djacquel** [comment]
As I've just said to @andreabedini [here](https://github.com/swcarpentry/website/issues/39#issuecomment-160627976), until there is no need to generate a page for each `people` or `project`, the way he is doing it, under `_data/people`, is ok.
