### ISSUE TITLE
Add links to surveys

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#100]
Relocated from https://github.com/swcarpentry/site/issues/1153: website should link to current surveys for inspection.

**Comment by maneesha** [comment]
Does this mean a link to the sample survey should appear in the operations guide on our website?

@ErinBecker  and I have been talking about revamping some of this content so we can talk about where this would fit.

**Comment by jduckles** [comment]
@maneesha Rather than the sample survey link, can we put a PDF export available from Survey Monkey in Design Survey -> Print onto files.software-carpentry.org? This is a much more useful version of the survey to share so people get an idea of what we ask.

**Comment by jduckles** [comment]
They're here. https://software-carpentry.org/assessment/
