### ISSUE TITLE
Add N8 consortium as partner

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#101]
Relocated from https://github.com/swcarpentry/site/issues/1178: University of Leeds is currently listed as partner, but should be N8 consortium http://www.n8research.org.uk/

**Comment by andreww** [comment]
@callaghanmt should probably look at this one.

**Comment by gvwilson** [comment]
@jduckles how should this be resolved?

**Comment by callaghanmt** [comment]
University of Leeds is the legal entity and signatory of the partnership agreement (and the one that pays the bills) and thus should be the listed partner.
