### ISSUE TITLE
link to membership information not clear

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/website-archive#1041]
I received this question by email, which points out that the membership information isn't clearly linked to from the SWC page. 

> Hi, I've been searching through the Software Carpentry web site and cannot find any information about what the membership dues are or what costs might be for joining and having workshops.  Data Carpentry has a page with different membership levels, costs, and what is the benefit of each level, but I have not been able to find a similar page for the Software Carpentry site (all clicks point back to the Governance page, which has no info posted other than minutes of meetings; I read the minutes, but no mention of costs was available.)  Can you advise?

**Comment by tracykteal** [comment]
The 'Join Us' page used to have Membership information, but now it redirects to Join on The Carpentries page which doesn't have that information. We could change the redirect, add something to the menu, or add something about Membership on the Join Carpentries page. The last one might be the best.

**Comment by tracykteal** [comment]
Nevermind, membership info is on the Carpentries Join page. So, we could add a 'Become a Member Organization' menu item on SWC to add clarity.

**Comment by jduckles** [comment]
Am I missing something? this is what I see on the SWC page.

![image](https://user-images.githubusercontent.com/119403/40283698-82f01988-5cd6-11e8-8f0d-3db2e80e439a.png)

**Comment by tracykteal** [comment]
On carpentries.org and datacarpentry.org the 'Become a Member' is under 'Join Us' rather than 'About'.
