### ISSUE TITLE
Relevance of struggles/disabilities in learner profiles

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/website-archive#1044]
Our learner profiles have a set of struggles/disabilities added through #576 (as a result of #558):

- celiac disease
- nearsightedness
- family with small children and undiagnosed depression
- attention deficit disorder

These seem to have been accepted without discussion (at least on GitHub, I may have missed a discussion elsewhere). 

I understand the thought, our learners are diverse and may be struggling with issues we don't see. However, these struggles/disabilities seem a bit out of place. I am not sure whether they are relevant in the context of our workshops. 

Open for discussion, and to kick this off I provocatively suggest too remove them.

**Comment by weaverbel** [comment]
Has this been addressed anywhere @lexnederbragt - am trying to tidy up issues.

**Comment by lexnederbragt** [comment]
No, not yet as far as I know.

**Comment by weaverbel** [comment]
I think this issue needs to be addressed in the instructor training repo - @ErinBecker @karenword - what do you think? That is really where we look at profiles.

**Comment by karenword** [comment]
I agree that, while this content technically lives here, it is probably best suited for discussion by the trainer community in the context of the [lesson that references it](http://carpentries.github.io/instructor-training/14-lesson-study/). @lexnederbragt how about bringing this up on the TTT repo to see if we can get a little more conversation going over there?

**Comment by weaverbel** [comment]
OK, I will leave this for @lexnederbragt to decide. Thanks @karenword

**Comment by lexnederbragt** [comment]
Good idea. Moved, closing here.
