### ISSUE TITLE
redirect from https://swcarpentry.github.io/ returns 404 error

### ISSUE THREAD

**Issue by arivers** [swcarpentry/website-archive#1049]
The redirect from `https://swcarpentry.github.io/` to `https://software-carpentry.org/` does not work.

It redirects to `https://software-carpentry.org/lessons.html`  but it should redirect to 
`https://software-carpentry.org/lessons/`

**Comment by jduckles** [comment]
These are fixed, some changes to `_config.yml` were made assuming the build environment was a bit more modern than it was. I've updated the ruby/bundle/jekyll stack in the build environment and all seems to be right with the world again.
