### ISSUE TITLE
404 page works locally only

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website-archive#1050]
If I  go to a page that does not exist like https://software-carpentry.org/abcd  I get a generic, unformatted 404 page.

If I do the same thing after building the site locally, like http://127.0.0.1:4000/abcd  I get the 404 page from here:  [/pages/404.html](https://github.com/swcarpentry/website/blob/gh-pages/pages/404.md)

**Comment by jduckles** [comment]
Fixed.
