### ISSUE TITLE
Better image for contact page

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website-archive#1051]
The image on the "contact" page (https://software-carpentry.org/contact/) is the torso of someone on a laptop with soda bottles and cups and plastic bags on the table.  Can we get a better image?

**Comment by weaverbel** [comment]
I replaced this with a placeholder image but it isn't showing yet. Am investigating.

**Comment by weaverbel** [comment]
Nice seascape up while I try to source something we can use that says Contact.
