### ISSUE TITLE
Display development dashboard with most recent first

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website-archive#1052]
Items in [development dashboard](https://software-carpentry.org/lessons/dashboard/) are in chronological order.  This should be in reverse chronological order so the most recent are on top.

**Comment by jduckles** [comment]
You can reverse the `for` loops in https://github.com/swcarpentry/website/blob/gh-pages/pages/lessons_dashboard.html with liquid's reverse syntax https://shopify.github.io/liquid/filters/reverse/
