### ISSUE TITLE
Delete patch branches?

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website-archive#1053]
There are a ton of very outdated patch branches in this repo.  Can we delete these to clean up the repo?

**Comment by jduckles** [comment]
Yes.

**Comment by maneesha** [comment]
Does anyone know an automated way to do this?

**Comment by weaverbel** [comment]
Where are they? I only see one branch.

**Comment by maneesha** [comment]
Hmm.. I thought I saw a ton of old branches a few days ago. Maybe @jduckles already deleted them?  If so OK to close.

**Comment by weaverbel** [comment]
Oh, that was me - I am trying to tidy up issues and stuff on all the websites!
