### ISSUE TITLE
Is there still a Software Carpentry Foundation with voting members?

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website-archive#1056]
Does this page still apply?

https://software-carpentry.org/scf/members/

**Comment by weaverbel** [comment]
@jduckles ?

**Comment by jduckles** [comment]
This is a @tracykteal question regarding new bylaws and voting rights. We can likely sunset this page, but I'm reluctant to do it until we have a redirect to the current list of voting members.

**Comment by tracykteal** [comment]
EC is in the process of updating the bylaws. Request for comment on the updates will go out in August. I think we can keep this page, and add to the top something to the effect of it being updated for The Carpentries and the timeline. @k8hertweck does that sound good?

**Comment by jduckles** [comment]
Closing as this is forthcoming. See: https://carpentries.org/blog/2018/07/ec-rfc-overview/
