### ISSUE TITLE
"Conversations" section needs updating

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website-archive#1060]
In the "Conversations" section of the [About us](https://software-carpentry.org/about/) page

* Sign up for newsletter redirects to https://carpentries.org/join/.  It should redirect to http://carpentries.org/newsletter/
* Follow us on Twitter should go to https://twitter.com/swcarpentryhttps://twitter.com/swcarpentry
* Browse our repositories on github should go to https://github.com/swcarpentry/

**Comment by weaverbel** [comment]
Fixed
