### ISSUE TITLE
Maps API has changed at Google

### ISSUE THREAD

**Issue by jduckles** [swcarpentry/website-archive#1062]
These commits comment out the maps on the website for now until we find out how to handle changes to the google API 33dda839c9c2a08b268d4851d4621e3d45862396 6101a96272751935347a7af93b5406c76482089d

Will revert as soon as I can sort out the API changes.

**Comment by jduckles** [comment]
If we're going to go OSM and Leaflet, we'll need to use something that does the marker clustering like Google. One option is: https://github.com/Leaflet/Leaflet.markercluster

**Comment by katrinleinweber** [comment]
Let's not overlook https://github.com/swcarpentry/amy/issues/1248 ;-)

**Comment by jduckles** [comment]
I've added Credit Card info to Google and replaced the existing API key with an updated one. So we're back in business with a Google-based approach for now.

**Comment by weaverbel** [comment]
Are we going to allow people to see instructor numbers on a map on the Carpentries website @jduckles ? I know the new page has the country flag but it would be good to provide a map view as well?

**Comment by olexandr-konovalov** [comment]
+1 for map. It's an excellent visualisation of the global community. I've used it a number of times when presenting Software Carpentry, and I really miss it now.

**Comment by gvwilson** [comment]
Ditto.

**Comment by jduckles** [comment]
FYI: Map is back and here: https://carpentries.org/instructors-map/
