### ISSUE TITLE
'Teaching and Hosting Guide' Link Broken on Workshops Page

### ISSUE THREAD

**Issue by elmorin** [swcarpentry/website-archive#1064]
On the workshops page of the website: 
https://software-carpentry.org/workshops/

The link to 'teaching and hosting guide' is broken.  

I believe it should be pointing to this page: 
https://docs.carpentries.org/topic_folders/hosts_instructors

**Comment by jduckles** [comment]
Thanks for pointing out the broken link @elyselouisemorin it is fixed now.
