### ISSUE TITLE
redirect not working

### ISSUE THREAD

**Issue by fmichonneau** [swcarpentry/website-archive#1066]
Redirect set up as part of #1065 doesn't seem to be working.

I think redirects are useful to avoid broken links, but I also don't think it's good practice to keep redirecting people from one site to the other. If they were looking for information about SWC we now send them over to carpentries.org. It doesn't make for a good user experience.

I suggest we either add a sentence on the page saying "The list of our instructors is now at carpentries.org/team/", or we remove the link in the navigation bar to this page.

**Comment by weaverbel** [comment]
The redirect is working now @fmichonneau - I will ask @maneesha what she would prefer as she was the one who raised it initially. I will then implement that.

**Comment by weaverbel** [comment]
@maneesha can you please work out what you want here and we can close this issue?

**Comment by maneesha** [comment]
Closing.  Looks like this has since been fixed.
