### ISSUE TITLE
Locations on instructor map

### ISSUE THREAD

**Issue by olexandr-konovalov** [swcarpentry/website-archive#1067]
Thank you @jduckles for restoring the map in #1062. Now I have a suggestion about changing the way how instructor locations are displayed on the map. At the moment, they are taken from the nearest international airport as recorded in AMY. As a result, for example, @pgmccann from St Andrews is shown in Edinburgh. I have entered the code for Leuchars (which is not an international airport, but has its code), although that may possibly miss me if someone will ask AMY to find everyone who is located near Edinburgh.

I think more precise location display (e.g. up to town where the institution is located) will help to members of institutions to find Carpentries representatives in their institution. 

![screen shot 2018-09-04 at 11 20 19](https://user-images.githubusercontent.com/5751387/45028167-dbae6a80-b03b-11e8-85b3-e7f3d9bf15c0.png)

**Comment by jduckles** [comment]
@alex-konovalov this is not an interface meant for finding instructors. We have an interface purpose built for identifying instructors, their teaching competencies etc in our [AMY tool](https://github.com/swcarpentry/amy), I'm going to close this issue, as at coarse global scale, you do show up in the circle on the northern UK. Thank you for taking the time to comment. I've raised an [issue in AMY](https://github.com/swcarpentry/amy/issues/1337) recently to propose some mechanism of affiliating members with institutions and organizations. Please weigh in if you have anything to add about how this might be usedl
