### ISSUE TITLE
Banner image for workshops is now missing on site

### ISSUE THREAD

**Issue by twhitehead** [swcarpentry/website-archive#107]
The default workshop template  contains a link to the following software carpentry banner (an image of the the software carpentry hammer logo thing).

http://software-carpentry.org/img/software-carpentry-banner.png

It is no longer there (as of over christmas sometime I believe) so many of the workshop pages now having a broken banner.  For example, from the top few upcoming ones,

https://abostroem.github.io/2016-01-03-aas/
https://andreww.github.io/2016-01-06-bristol/
https://uwescience.github.io/2016-01-07-uw/
http://smallerthings.org/2016-01-07_asu_physics/
https://computecanada.github.io/2016-01-09-uwo/

Thanks!  -Tyson

**Comment by rgaiacs** [comment]
@twhitehead Thanks very much for report the problem.

I pushed a fix to https://github.com/swcarpentry/workshop-template/ (see https://github.com/swcarpentry/workshop-template/commit/8d0905bebdb5d203e6118dbe645794b7bb16064d) but people will need to update their repository.

**Comment by rgaiacs** [comment]
@gvwilson Could you add a rule to `.htaccess`?

**Comment by gvwilson** [comment]
Good catch - very sorry about missing this one.

**Comment by gvwilson** [comment]
@rgaiacs does the SVG image render properly in the header?  The old 
image was a PNG.

**Comment by rgaiacs** [comment]
> does the SVG image render properly in the header?

![screen shot 2015-12-28 at 09 01 27](https://cloud.githubusercontent.com/assets/1506457/12017722/990e9c9a-ad41-11e5-80d5-e2be76745305.png)

![screen shot 2015-12-28 at 09 01 42](https://cloud.githubusercontent.com/assets/1506457/12017725/a09b391e-ad41-11e5-993b-6a792d665074.png)

**Comment by gvwilson** [comment]
Temporarily fixed in 8a19e7dcff by creating `./img/software-carpentry-banner.png` (copying in file from old site). We'll fix this in the new template...

**Comment by twhitehead** [comment]
Thanks everyone.

**Comment by gvwilson** [comment]
Thank _you_ - can you please confirm all is good?

**Comment by rgaiacs** [comment]
> can you please confirm all is good?

**Yes.**
