### ISSUE TITLE
Links to Maintainers bios are broken

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website-archive#1071]
On the lessons page (https://software-carpentry.org/lessons/)
the lesson maintainers names are linked to the old instructor bios that used to be on the SWC website.  These broken links should be removed.

@ErinBecker  Would you suggest having them link to the Maintainer's github profile or not link to anything?

**Comment by ErinBecker** [comment]
Let's just remove the links for now.

**Comment by jduckles** [comment]
See carpentries/carpentries.org#402 I've just submitted a PR to the carpentries site to fix this. 

Merging:
1. https://github.com/carpentries/carpentries.org/pull/402
2. https://github.com/swcarpentry/website/pull/1072

Should fix this up.
