### ISSUE TITLE
Redirect to new operations guide

### ISSUE THREAD

**Issue by arokem** [swcarpentry/website-archive#1073]
This page is empty: https://software-carpentry.org/workshops/operations/

And similarly other related pages: https://software-carpentry.org/checklists/helper/

Would be good to redirect to https://docs.carpentries.org/

**Comment by maneesha** [comment]
Thanks for catching this @arokem 
I'll work on getting the redirects set up.

**Comment by maneesha** [comment]
Trying to fix this with a1b6faf832dee0acd492222929395ed05101ebd2
This is working for me locally but not on the live version.  Still looking into why.

**Comment by maneesha** [comment]
Working now... looks like it just takes a day to propagate changes live.
