### ISSUE TITLE
Document process for adding a workshop, write a blog post, etc.

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#108]
Add docs explaining how to add a workshop, write a blog post, etc.

**Comment by gvwilson** [comment]
@jduckles is this worth doing at this point, or are we going to reorganize the site and blog in the next 2-3 months?

**Comment by jduckles** [comment]
@weaverbel This one would be great for you to help us with.

**Comment by weaverbel** [comment]
@jduckles Will check it out soon and yes I can help.

**Comment by jduckles** [comment]
I've adapted our lesson contribution guide (CONTRIBUTING.md) to the website. It could use some more step-by-step instructions on creating a blog post. https://github.com/swcarpentry/website/blob/gh-pages/CONTRIBUTING.md

**Comment by weaverbel** [comment]
I have done the blog post guide for CONTRIBUTING.md so I might close this issue now.
