### ISSUE TITLE
CSS does not  load on https

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website-archive#112]
http://software-carpentry.org/
vs
https://software-carpentry.org/

http://software-carpentry.org/workshops/index.html
vs
https://software-carpentry.org/workshops/index.html

**Comment by gvwilson** [comment]
Aaarrgghh... thanks.

**Comment by rgaiacs** [comment]
Just replace `https://` with `//`everywhere. I can send a pull request soon.

**Comment by gvwilson** [comment]
Fixed by #114 - @maneesha please verify?

**Comment by gvwilson** [comment]
Fixed.
