### ISSUE TITLE
Lesson table issue

### ISSUE THREAD

**Issue by sstevens2** [swcarpentry/website-archive#1164]
Some accessibility issues with the lessons table that came up in a meeting with local accessibility expert: 
 
- No accessible names for the links in the table - Recommend changing these icons to descriptive links instead.
- Tool tips (that show up upon hovering over a link) don't have unique names. So the reference, lesson repo, and site all say the same lesson name instead of unique names for each link. - recommend making these unique for each link.
- Tool tip is only reachable via hover rather than by hover and focus (via tabbing) - recommend adding this feature but especially not sure how to change this one.

Not sure where these are changeable in the template but let me know if there is a particular place I should look.  Happy to make a PR if I can but not sure I know where and what to change.

**Comment by maneesha** [comment]
Hi @sstevens2  Thanks so much for bringing this all to our attention.  To be sure, you are talking about the tables  on [this page](https://software-carpentry.org/lessons/)?  

I admit I don't know enough about accessibility standards to address this myself, but if you have been working with an accessibility expect, perhaps they can give us a few pointers?

The template was forked long ago from [this theme](https://phlow.github.io/feeling-responsive/).  It has not stayed up to date with the theme so there may be features that the theme now includes that it didn't back then.  There's a lot of documentation about the theme now.

I'm leaving this issue open for now as I want to have a space for people to discuss and contribute ideas.

**Comment by ErinBecker** [comment]
Thank you @sstevens2 for raising this issue. I think I can take care of the first two points you mentioned, but likely not until January. For the third point, I'll need to do some research. Would be grateful to anyone who sees this in the meantime and suggests any resources. 

More broadly, we'll be releasing The Carpentries Strategic Plan soon and have a full accessibility overhaul of our websites on that plan. 👍

**Comment by maneesha** [comment]
Hi @sstevens2 I'm trying to go through some rather old issues across our websites.  Does this sample cover what you were thinking of in the first two points?  Let me know and I can continue this for the rest of the table (and I will check out the lesson pages on our other sites too).


![swc_lesson_table](https://user-images.githubusercontent.com/829690/115057836-83f26400-9eb2-11eb-9836-7b70d953fac9.gif)

**Comment by sstevens2** [comment]
Thanks @maneesha! I think this covers the 2nd point listed above very well.  The first point is about having descriptive links instead of icons in the table and I'm not sure how to implement the 3rd one actually.  I'm alright with closing this issue with the changes you've made @maneesha.

**Comment by maneesha** [comment]
This is partly addressed by #1205 

Closing this for now.  Other issues will be addressed with other larger accessibility overhauls.
