### ISSUE TITLE
Hover Text for Spanish Lessons in table

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website-archive#1206]
On the [Software Carpentry lessons page](https://software-carpentry.org/lessons/) we have tables of lessons with icons for the main site, the GitHub repo, reference guide, and instructor notes.  The recent PR #1205 updated the hover text for all these icons to be more descriptive.  For example, rather than just saying "The Unix Shell" for all icons in that row, the hover text now reads The Unix Shell Main Site, The Unix Shell GitHub Repo, etc.  For example:

![swc_lesson_table](https://user-images.githubusercontent.com/829690/115436273-cd0b2680-a1d8-11eb-8572-cd4627e32096.gif)

I'd like to add hover text for the Spanish lessons as well so that instead of just saying "La Terminal de Unix" it says the equivalent of what the English language tables do.  Do we have any fluent Spanish speakers who would be able to translate the hover text?

**Comment by santisoler** [comment]
Hi @maneesha !
I can tackle it. I'll open a PR so you and preferably any other Spanish speaker can review it.
