### ISSUE TITLE
Missing information about dependencies

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/website-archive#131]
I was installing the website on a fresh server and found out some additional dependencies.

One of Jekyll deps required `execjs`, and fresh Python3 required `python3-yaml`.

**Comment by pbanaszkiewicz** [comment]
And also `github` package from PyPI, and `pip` to install it.

**Comment by pbanaszkiewicz** [comment]
Actually, which github package is required, precisely? There are tons on PyPI matching 'github'.

**Comment by pbanaszkiewicz** [comment]
For future reference: it seems `pygithub` is the one we use.

**Comment by gvwilson** [comment]
Closed in favor of #61.
