### ISSUE TITLE
mentoring list not shown

### ISSUE THREAD

**Issue by dbrunson** [swcarpentry/website-archive#132]
The Mentoring list (http://lists.software-carpentry.org/mailman/listinfo/mentoring_lists.software-carpentry.org) isn't listed on the join page: http://software-carpentry.org/join/ 
(@jduckles)

**Comment by rgaiacs** [comment]
mentoring@lists.software-carpentry.org is used by the Mentoring Subcommittee for discussion of their activities, e.g. planning for post workshop debriefing.

@dbrunson The name is confusing. Change the name to "Mentoring Subcommittee" will help?

**Comment by jduckles** [comment]
@rgaiacs at our instructor training we had significant interest in participation in the Mentoring subcommittee. So I was suggesting they sign up. We do need to communicate subcommittee email lists and how people can join them, or even just lurk in the discussions. So I am against hiding them away, they should be publicly listed.

**Comment by gvwilson** [comment]
+1 to listing - we're an open org.
