### ISSUE TITLE
What will it take to get this site to render properly on GitHub?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#136]
What do we have to change in _config.yml to get this site to render properly on GitHub?  Right now, http://swcarpentry.github.io/website/ is completely unstyled.

**Comment by wking** [comment]
On Thu, Jan 07, 2016 at 02:08:37AM -0800, Greg Wilson wrote:

> What do we have to change in _config.yml to get this site to render
> properly on GitHub?  Right now,
> http://swcarpentry.github.io/website/ is completely unstyled.

Developer tools [1](https://developer.mozilla.org/en-US/docs/Tools) are good for this sort of debugging.  In this
case, the console [2](https://developer.mozilla.org/en-US/docs/Tools/Web_Console) shows:

  ReferenceError: $ is not defined     website:1020:2

And clicking on ‘website:1020:2’ takes me down to a line with:

  <script>
    $('p[data-toggle="tooltip"]').tooltip({html: true, placement: "bottom"});
  </script>

So I expect you're just missing a jQuery load, or you intended to
remove jQuery and forgot to remove this line when doing so.

**Comment by gvwilson** [comment]
Viewing source on the home page, the CSS links are 
`/assets/css/bootstrap.css' and similar.  Given that the URL is 
`http://swcarpentry.github.io/website`, I'm guessing that another 
required change is to set `url` to `http://swcarpentry.github.io` and 
`baseurl` to `/website` in `_config.yml`.
