### ISSUE TITLE
r-discuss list removed from mailing lists

### ISSUE THREAD

**Issue by jdblischak** [swcarpentry/website-archive#139]
I noticed that the [r-discuss](http://lists.software-carpentry.org/mailman/listinfo/r-discuss_lists.software-carpentry.org) list was removed from the list of mailing lists on the [join](http://software-carpentry.org/join/) page of the SWC website. What was the reasoning for this? Can it be added back? It was already difficult for new instructors to find the R-specific mailing list, and now it is all but impossible.

**Comment by gvwilson** [comment]
That was a simple editing mistake - I'll get it back in right now.

**Comment by jdblischak** [comment]
Thanks!
