### ISSUE TITLE
Formatting of blockquotes is unpleasant

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#14]
See for examples `/testimonials/` - the use of angle quotes etc. is trying to be clever, but isn't visually appealing.

**Comment by todrobbins** [comment]
I can take this on. The quotes need to be differentiated from the main body as well. Right now they all kind of blend together.

**Comment by todrobbins** [comment]
Should I fork?

**Comment by gvwilson** [comment]
Yes please, and thank you - I appreciate the help.
Greg
