### ISSUE TITLE
Workshop calendar not displaying upcoming workshops

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#143]
Relocated from https://github.com/swcarpentry/site/issues/1223 - calendar on http://software-carpentry.org/workshops/ is not showing any upcoming workshops.

**Comment by gvwilson** [comment]
@pbanaszkiewicz we recently merged changes to bin/get-amy.py that may have broken the calendar - can you please check?

**Comment by gvwilson** [comment]
Commented out use of -t (tags) flags in call to bin/get-amy.py in Makefile in 7da278d32 - we are now getting workshops data into the _data/amy.yml file, but the calendar is still not displaying correctly.

**Comment by gvwilson** [comment]
More information:
1.  Using "-t SWC -t DC" in the call to bin/get-amy.py definitely broke things: no workshops were fetched at all. @pbanaszkiewicz can you please check this?
2.  Once those flags are removed, _site/workshops.ics builds correctly, and when loaded into a desktop calendar application on my Mac, shows all of the upcoming events.
3.  When workshops.ics is downloaded from the website and loaded into a calendar app, the events display correctly as well.
4.  But the calendar on software-carpentry.org still does not display the events. This implies the breakage is on Google's end, or caching, or something like that. @wking can you see what's wrong?

**Comment by pbanaszkiewicz** [comment]
@gvwilson:

`-t SWC -t DC` is ADD, not OR. We don't have any SWC workshops that simultaneously are DC workshops. This is intended, as in future you may want to do something like `-t DC -t TTT` for example.

If you want to list both events that have either SWC or DC tag, then you can do two calls.

**Comment by gvwilson** [comment]
Ah - that could be clearer in the docs :-)  Can you please provide an 
"OR" option?  I'd like to keep the number of calls to a minimum.

**Comment by pbanaszkiewicz** [comment]
Hmmm, I could do:
`--tags-any=SWC,DC`
and
`--tags-all=SWC,TTT`

Would that work?

**Comment by pbanaszkiewicz** [comment]
@gvwilson, after some more thought I'm against adding OR option that requires a backend change. I'd rather just make two requests and then merge.

**Comment by gvwilson** [comment]
...so get-amy.py has to make two calls rather than one, merge two lists, 
and sort by date, keeping tag information?  If you want to implement it 
and maintain it, I still think it's less robust than one call (the 
network is always the biggest point of failure), but it's your call.  
Biggest headache now is figuring out why the calendar doesn't display, 
but that's the website, not AMY.

**Comment by pbanaszkiewicz** [comment]
@gvwilson I'm in the middle of https://github.com/swcarpentry/amy/issues/639 make AMY API a better place and I just don't want to change filtering in `published-events` part over again.

**Comment by gvwilson** [comment]
Sure - we'll run get-amy.py unfiltered for the moment, then re-sync once 
the calendar bug is sorted.

**Comment by gvwilson** [comment]
Now working - presumably the problem was a glitch during server migration.
