### ISSUE TITLE
Helper or instructor checklist: bring small notepad

### ISSUE THREAD

**Issue by kbroman** [swcarpentry/website-archive#152]
I find it useful to bring a small notepad to workshops, to write down bits of code for participants. 

(But I often forget and end up writing on scraps of paper or the side of coffee cups. I [mentioned this on twitter](https://twitter.com/kwbroman/status/687001735248900096) and @gvwilson [suggested filing an issue](https://twitter.com/gvwilson/status/687041375183831040).)

**Comment by jduckles** [comment]
closed by #414
