### ISSUE TITLE
How to integrate the Version 4 material?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#192]
The old website built the Version 4 material then cp'd it into a sub-directory of the site directory after the latter had been built.  This was clumsy, but it kept all the PNGs and PDFs from V4 out of the main site repo (which in turn kept its size down considerably). I propose that we:
1.  create a new subdomain v4.software-carpentry.org
2.  put the V4 stuff there
3.  update the links in our lessons and website
4.  add a suitable rule to a .htaccess file in website to redirect people

I estimate this will take about 6 hours of work.

**Comment by wking** [comment]
On Sat, Jan 23, 2016 at 02:27:28PM -0800, Greg Wilson wrote:

> 1.  create a new subdomain v4.software-carpentry.org
>    …

This sounds reasonable to me.

**Comment by pbanaszkiewicz** [comment]
@gvwilson I can create the `v4.swc.org` server at Rackspace and get the v4 lessons over there.

**Comment by gvwilson** [comment]
@jduckles ?  Creating the v4 domain is the easy part; converting the 
lessons to have the same look and feel as our existing stuff will take 
me a few hours.

**Comment by jduckles** [comment]
@pbanaszkiewicz I'm assuming this will just be a vhost on the existing VM? 
If not, Is it worth the maintenance overhead of a new VM for this? 

Alternatively: Are these just static assets? We can just host them out of an object storage bucket if that's the case. I just tested this and it will be straight forward once I have access to the directory tree with the assets styled the way @gvwilson wants it.

**Comment by pbanaszkiewicz** [comment]
@jduckles yes, I was offering to create a "vhost" on our files & main website server.

**Comment by jduckles** [comment]
Ok, well for now v4.swc.org points to the VM we host www. & files. from. I think a storage bucket is a better hands-off, longterm solution if it will work though.
