### ISSUE TITLE
current and past workshop lists contain all workshops 

### ISSUE THREAD

**Issue by tracykteal** [swcarpentry/website-archive#193]
The current and past workshop pages:
http://software-carpentry.org/workshops/
http://software-carpentry.org/workshops/past/

show all workshops - SWC, DC and Instructor Training

It would be good to just include SWC, or have in the table what each one is/was.

**Comment by gvwilson** [comment]
Please check after #468 is merged.

**Comment by gvwilson** [comment]
@tracykteal or @ErinBecker please confirm this can be closed.

**Comment by tracykteal** [comment]
LGTM. Thanks for updating.

**Comment by gvwilson** [comment]
Thanks - sorry it took so long.
