### ISSUE TITLE
Faces do not show up when mousing over biographies

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#2]
Go to `/team/`, move the mouse over a biography - should see an image (the person's face), but instead we see the text of the `<img ...>` link. The Javascript for the popup works on main web site's http://software-carpentry.org/pages/team.html page. (Note that the same problem occurs on the `/scf/` page, which uses the same snippets of HTML.)

**Comment by wking** [comment]
I haven't actually looked at the backing code, but Firefox's developer console reports a few problems:

![team](https://cloud.githubusercontent.com/assets/209920/11390909/2b7b17ce-9303-11e5-8b37-e96e84b04ff0.png)

**Comment by gvwilson** [comment]
Hm - the syntax errors are from the geoJson file.  The TypeError saying 
that ${...}.tooltip is not a function surprises me - it's a standard 
jQuery function (http://api.jqueryui.com/tooltip/).  I'm loading 
javascript.min.js right before setting the behavior of tooltips.  I've 
tried changing the code to:

   $('p[data-toggle="tooltip"]').tooltip({content: function(){return 
element.attr('title');}});

but that doesn't do any better - still gets the 'tooltip is not a 
function' message.  I'm missing something obvious...
G

On 2015-11-25 7:29 AM, W. Trevor King wrote:

> I haven't actually looked at the backing code, but Firefox's developer 
> console reports a few problems:
> 
> team 
> https://cloud.githubusercontent.com/assets/209920/11390909/2b7b17ce-9303-11e5-8b37-e96e84b04ff0.png
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/swcarpentry/website/issues/2#issuecomment-159524712.

## 

Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by FranciscoCanas** [comment]
I think the tooltip() function is a [jquery-ui method](http://api.jqueryui.com/tooltip/), not in standard JQuery. 

Alternatively, there is a boostrap tooltip method in the [boostrap API](http://www.w3schools.com/bootstrap/bootstrap_tooltip.asp).

I could not find either jquery-ui or bootstrap as dependencies in the project, so it makes sense that you're getting the 'tooltip is not a function' error. Do you want to add either of these dependencies?

**Comment by gvwilson** [comment]
Ah - didn't realize the difference between jquery and jquery-ui. We've 
already got jquery (I think - assets/js/javascript.js), so it probably 
makes more sense to use jquery-ui than to add bootstrap. Can you please?

**Comment by FranciscoCanas** [comment]
After digging some more, I went with using bootstrap's tooltips.js dependency for two reasons:
1 - The existing code was written using bootstrap's tooltip API, not jquery-ui's. 
2 - jquery-ui doesn't support html markup in the title attribute anymore, and required more fiddling.

Let me know if you still prefer using jquery-ui, and I can rework it.

**Comment by gvwilson** [comment]
Bootstrap is fine - any way to get it to superimpose over the text 
instead of inserting into the page, as the old one did?

**Comment by FranciscoCanas** [comment]
I've been looking into this one again to get the superimposed tooltip. Which version of the site had the working superimposed ones? I'd like to see what dependencies that version has, because i'm having trouble getting it to work with the current version of bootstrap's tooltip.js.

**Comment by gvwilson** [comment]
See http://software-carpentry.org/pages/team.html for the old 
implementation - image appears superimposed.  Repo is 
https://github.com/swcarpentry/site (but is large).
