### ISSUE TITLE
Code of conduct refers to 'conference organisers'

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/website-archive#208]
In http://software-carpentry.org/conduct/:

> Attendees violating these rules may be asked to leave the event at the sole discretion of the conference organizers without a refund of any charge that may have been levied.

Perhaps use 'event organisers' instead? Or just organisers?

In addition, the code covers 'Software Carpentry events and discussions'; can one write 'those violating may be asked to leave the event or discussion'?

**Comment by gvwilson** [comment]
:+1: to Lex's suggested changes.
