### ISSUE TITLE
Jekyll upgrade on GitHub Pages

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/website-archive#211]
https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

I know we don't host on GH pages, but it's still worth to be compatible.

**Comment by pbanaszkiewicz** [comment]
I'll take a look to see if anything needs to be reworked. (Probably yes…)

**Comment by rgaiacs** [comment]
@pbanaszkiewicz Please look at https://jekyllrb.com/docs/upgrading/2-to-3/.

I'm concern about

> # Layout metadataPermalink
> 
> Introducing: layout. In Jekyll 2 and below, any metadata in the layout was munged onto the page variable in Liquid. This caused a lot of confusion in the way the data was merged and some unexpected behaviour. In Jekyll 3, all layout data is accessible via layout in Liquid. For example, if your layout has class: my-layout in its YAML front matter, then the layout can access that via {{ layout.class }}.
