### ISSUE TITLE
Polling remote servers during site rebuild

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/website-archive#223]
Some things I noticed:
1. `_data/amy.yml` is hard-coded in the repository and only updated from time to time
2. AMY threw [`429: Too many requests`](https://httpstatuses.com/429) during `make amy` call
3. Even though some things errored-out, the build carried on and finally the website went down…

(Ignoring °3, 1&2 will end up with website build with historical data…)

The errors I can see here:
1. `_data/amy.yml` shouldn't be included in the repository. It should be regenerated upon building OR it should have some static workshops saved and the file should be ignored
2. Website should use a token for bigger rate limit (100/day for anonymous users, 1000/day for logged in users) OR log into one of AMY accounts
3. `Makefile` should contain files like `_data/amy.yml` listed as dependencies for targets; website rebuild script should proceed if and only if all steps succeeded.

**Comment by gvwilson** [comment]
On 2016-02-05 6:26 PM, Piotr Banaszkiewicz wrote:

> Some things I noticed:
> 1. |_data/amy.yml| is hard-coded in the repository and only updated 
> from time to time

It's stored in the repo so that people who don't have access to AMY can 
still build the website.  The cron job on the server overwrites it there 
every time a build is done, and I check in updated copies every once in 
a while.

> 1. AMY threw |429: Too many requests| https://httpstatuses.com/429 
>    during |make amy| call

Do we know why?

> 1. Even though some things errored-out, the build carried on and 
>    finally the website went down…
> 
> (Ignoring °3, 1&2 will end up with website build with historical data…)
> 
> The errors I can see here:
> 1. |_data/amy.yml| shouldn't be included in the repository. It should 
> be regenerated upon building OR it should have some static workshops 
> saved and the file should be ignored

I came to a different conclusion - talk this through on a hangout?

> 1. Website should use a token for bigger rate limit (100/day for 
>    anonymous users, 1000/day for logged in users) OR log into one of AMY 
>    accounts

Your call.

> 1. |Makefile| should contain files like |_data/amy.yml| listed as 
>    dependencies for targets; website rebuild script should proceed if and 
>    only if all steps succeeded

Mm... does that mean that (for example) a new blog post won't show up if 
AMY is down?

Thx,
G

## 

Dr Greg Wilson
Director of Instructor Training
Software Carpentry Foundation

**Comment by pbanaszkiewicz** [comment]
Hello Greg,

On Sat, Feb 6, 2016 at 2:54 AM, Greg Wilson notifications@github.com
wrote:

> On 2016-02-05 6:26 PM, Piotr Banaszkiewicz wrote:
> 
> > Some things I noticed:
> > 1. |_data/amy.yml| is hard-coded in the repository and only updated
> > from time to time
> 
> It's stored in the repo so that people who don't have access to AMY can
> still build the website. The cron job on the server overwrites it there
> every time a build is done, and I check in updated copies every once in
> a while.
> 
> > 1. AMY threw |429: Too many requests| https://httpstatuses.com/429
> >    during |make amy| call
> 
> Do we know why?

The server takes 48 calls - almost half of all. The other half may be
people trying to build the website locally?

> > 1. Even though some things errored-out, the build carried on and
> >    finally the website went down…
> > 
> > (Ignoring °3, 1&2 will end up with website build with historical data…)
> > 
> > The errors I can see here:
> > 1. |_data/amy.yml| shouldn't be included in the repository. It should
> > be regenerated upon building OR it should have some static workshops
> > saved and the file should be ignored
> 
> I came to a different conclusion - talk this through on a hangout?

Definitely - I'm driving home soon, so talk to you in my afternoon?

> > 1. Website should use a token for bigger rate limit (100/day for
> >    anonymous users, 1000/day for logged in users) OR log into one of AMY
> >    accounts
> 
> Your call.
> 
> > 1. |Makefile| should contain files like |_data/amy.yml| listed as
> >    dependencies for targets; website rebuild script should proceed if and
> >    only if all steps succeeded
> 
> Mm... does that mean that (for example) a new blog post won't show up if
> AMY is down?

It depends on how we implement the makefile and building script.

Cheers,
Piotr

**Comment by gvwilson** [comment]
On 2016-02-06 4:30 AM, Piotr Banaszkiewicz wrote:

> > > 1. AMY threw |429: Too many requests| https://httpstatuses.com/429
> > >    during |make amy| call
> > 
> > Do we know why?
> 
> The server takes 48 calls - almost half of all. The other half may be
> people trying to build the website locally?

Hm - I count 2 + T calls to 'fetch_info' in 'get-amy.py', where T is the 
number of tags.  From the Makefile, that's 3, so 5 calls for a site 
rebuild.  Even with 3 or 4 people doing builds, that's still a lot missing.

> Definitely - I'm driving home soon, so talk to you in my afternoon?
> 
> Monday?  (I'm not supposed to be working weekends.)
> 
> > > 1. |Makefile| should contain files like |_data/amy.yml| listed as
> > >    dependencies for targets; website rebuild script should proceed if and
> > >    only if all steps succeeded
> > 
> > Mm... does that mean that (for example) a new blog post won't show up if
> > AMY is down?
> 
> It depends on how we implement the makefile and building script.
> Yes - yes it does :-)
> Cheers,
> G

## 

Dr Greg Wilson
Director of Instructor Training
Software Carpentry Foundation

**Comment by pbanaszkiewicz** [comment]
Hi Greg,

On Sat, Feb 6, 2016 at 1:03 PM, Greg Wilson notifications@github.com
wrote:

> On 2016-02-06 4:30 AM, Piotr Banaszkiewicz wrote:
> 
> > > > 1. AMY threw |429: Too many requests| https://httpstatuses.com/429
> > > >    during |make amy| call
> > > 
> > > Do we know why?
> > 
> > The server takes 48 calls - almost half of all. The other half may be
> > people trying to build the website locally?
> 
> Hm - I count 2 + T calls to 'fetch_info' in 'get-amy.py', where T is the
> number of tags. From the Makefile, that's 3, so 5 calls for a site
> rebuild. Even with 3 or 4 people doing builds, that's still a lot missing.

There are 48 automatic rebuilds per day; if each rebuild "costs" 5 AMY
calls then we exceed quota in 6 hours every day…

**Comment by gvwilson** [comment]
On 2016-02-06 7:11 AM, Piotr Banaszkiewicz wrote:

> There are 48 automatic rebuilds per day; if each rebuild "costs" 5 AMY
> calls then we exceed quota in 6 hours every day…

Ah, OK, that makes sense.  Yes, up the quota.

Thx,
G

**Comment by pbanaszkiewicz** [comment]
I manually bumped the AMY API request limit on production to 500/day for anonymous user, 2000/day for authorized user. This is temporary. See https://github.com/swcarpentry/amy/issues/691 for details.

**Comment by gvwilson** [comment]
Is this still an issue?
