### ISSUE TITLE
Blogpost doesn't render at all

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/website-archive#224]
http://software-carpentry.org/blog/2016/02/swdcretreat2015-university_course.html

Source: https://github.com/swcarpentry/website/blob/gh-pages/_posts/2016/02/2016-02-03-swdcretreat2015-university_course.html

I have no idea what's wrong with this post, though.

**Comment by pbanaszkiewicz** [comment]
Ah, maybe it should have `.md` extension, not `.html`?

**Comment by gvwilson** [comment]
The title is also odd: what is "SWDCRetreat2015" going to mean to our 
audience?  And the content seems to be missing all the paragraph tags, 
but have everything else.  And ampersands are un-escaped.  And there are 
places where ' is matched by ".

**Comment by rgaiacs** [comment]
The render problem was fixed by #222.
