### ISSUE TITLE
Create script to summarize changes to repos for mentoring summaries

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#249]
1.  Pull titles of PRs merged over the last two weeks from core lessons.
2.  Send to mentoring subcommittee for discussion in mentoring meetings and inclusion in their regular reports.

**Comment by wking** [comment]
I still think it will be more useful to have lesson maintainers cut
releases with changelogs or release notes [1].  That makes it easier
to highlight important changes vs. typo fixes.

On Fri, Feb 12, 2016 at 12:43:20PM -0800, Greg Wilson wrote:

> 1.  Pull titles of PRs merged over the last two weeks from core lessons.

IPython has a tool to do this [2](https://github.com/ipython/ipython/blob/master/tools/github_stats.py), but you can also generate that
information from your local repositories:

  $ REPOS='shell-novice git-novice hg-novice sql-novice-survey python-novice-inflammation r-novice-inflammation r-novice-gapminder matlab-novice-inflammation make-novice instructor-training'
  $ for REPO in $REPOS

> do
>   echo "# $REPO" &&
>   echo '' &&
>   (
>     cd $REPO &&
>     git fetch -q origin &&
>     git --no-pager log --first-parent --merged --format='%s%n%b%n' 'origin/gh-pages@{2 weeks}..origin/gh-pages'
>   )
> done

assuming you fetch often enough that your reflog entry for two weeks
ago is close to what was live on GitHub two weeks ago.  Output looks
like:

  # shell-novice

  Merge pull request #305 from btel/fix_pipeline_reading_exercise
  revise command from 'pipeline reading' exercise (fixes #280)

  Merge pull request #302 from iamc/gh-pages
  Clarify pipe chaining

  Merge pull request #303 from lexnederbragt/patch-2
  Remove 'Unnumbering' callout box

  Merge pull request #297 from chiefrydbeck/gh-pages
  removed a typo
  …

  # git-novice

  Merge pull request #231 from mbonsma/tracking_changes_exercise
  Add 'choosing a commit message' exercise solution

  Merge pull request #223 from amueller/detached_head_challenge
  Add challenge : detached head

  Merge pull request #221 from aappling-usgs/gh-pages
  Add new challenge on how to use GitHub GUI
  …

[1]: To mentoring@, although lists.software-carpentry.org seems to be down now.
     Subject: Change-logs or release notes for lessons? (was: something to include in mentoring summaries)
     Date: Wed, 10 Feb 2016 10:29:34 -0800
     Message-ID: 20160210182934.GV4265@odin.tremily.us

**Comment by gvwilson** [comment]
Doesn't have to be either/or, and they'd like more frequent updates.

**Comment by wking** [comment]
On Fri, Feb 12, 2016 at 02:51:24PM -0800, Greg Wilson wrote:

> Doesn't have to be either/or…

Fair enough.

> … and they'd like more frequent updates.

If mentoring cares about sub-release changes, either:
- They're really interested in helping develop the lesson, in which
  case they should subscribe to the repo.
- The lesson is not getting released often enough, and interesting
  changes and useful fixes have accumulated since the last release.

And that's not either/or either ;).  But I think autogenerated
merge-dumps are a stop-gap and not a long-term solution.

**Comment by weaverbel** [comment]
I think things have moved on so I am closing this here.
