### ISSUE TITLE
Fix: clustering markers on the map

### ISSUE THREAD

**Issue by pbanaszkiewicz** [swcarpentry/website-archive#259]
Markers cluster single cities where instructors are based, while it should be one marker per instructor.

**Comment by pbanaszkiewicz** [comment]
@gvwilson: what is the file http://software-carpentry.org/instructors.json created by?

**Comment by gvwilson** [comment]
Not quite - the markers are supposed to cluster (the map would be 
unreadable otherwise), but the numbers shown in each cluster are wrong, 
presumably because instructors' names are being run together. See also 
#62 #110 #115

Thanks,
Greg

**Comment by gvwilson** [comment]
It is created by Jekyll template expansion from `pages/instructors.json` 
using `_data/amy.yml` data.

**Comment by pbanaszkiewicz** [comment]
Okay, this issue is duplicate of #110. Closing for now, let's move the discussion there.
