### ISSUE TITLE
Need better layout for the "join" page

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#27]
`/join/` probably needs something more eye-catching than repetition of "A sub-list for discussion of activities in".  Would a map with pins for regional lists be useful?

**Comment by SamuelMoraesF** [comment]
I'll create an index file inside `_data` folder and parse it to a map :+1:

**Comment by gvwilson** [comment]
That would be welcome, but getting the map of instructor and workshop 
locations working again is a higher priority - would you be able to 
tackle that?  We've got several pieces of a solution lying around, and 
I'd be happy to chat.
