### ISSUE TITLE
Links to comments roll on blog page incorrect

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website-archive#270]
From an email:

> Hello,
> Was just browsing http://software-carpentry.org/blog/index.html and in attempting to follow comments on the right pane I discovered that the URLs for the posts associated with the comments (e.g. Welcome to the 2016 Steering Committee! currently the most recent) are using localhost as the domain, or that IP or the IP 0.0.0.0 (it’s not consistent). Replicated in two Windows browsers (Edge, Firefox).

**Comment by jduckles** [comment]
The only place I can see this coming from is our `Makefile` has

```
bundle exec jekyll serve --config _config.yml,_config_dev.yml --future
```

The only reference to localhost:4000 is in `_config_dev.yml`

@gvwilson @pbanaszkiewicz, should we be loading _config_dev.yml in production?

**Comment by gvwilson** [comment]
We definitely should _not_ be using _config_dev.yml in production.

**Comment by pbanaszkiewicz** [comment]
Building script has currently this inside it:

```
make amy
make dashboard
make includes
jekyll build
```

I changed the last line to:

```
jekyll build --config _config.yml
```

Let's see if it has any effect.

**Comment by pbanaszkiewicz** [comment]
Actually I don't think the building script is to blame.

Isn't it something wrong with Disqus?

See:
1. https://github.com/swcarpentry/website/blob/gh-pages/blog/index.html#L13
2. There's `0.0.0.0` or `localhost` or `software-carpentry.org` used… `_config_dev.yml` only mentions the localhost.

**Comment by jduckles** [comment]
Seems to have fixed it, closing.

**Comment by jduckles** [comment]
Nevermind, I thought that had fixed it. _sigh_ I thought that too, but I can't find anything in discuss pointing toward `localhost:4000`
