### ISSUE TITLE
Favicon not displaying properly

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#30]
The old Feeling Responsive favicon.ico file still seems to be displayed, even though `assets/img/favicon.ico` is the Software Carpentry favicon.

**Comment by todrobbins** [comment]
The favicon is not in the root directory, where `_config.yml` specifies, and the Feeling Responsive assets are still in `/assets/img/`.

In the existing repo (https://github.com/swcarpentry/site) the favicon is in the root directory.

**Comment by gvwilson** [comment]
#57 puts favicon.ico in the root directory, and it's then in 
_site/favicon.ico after a local build, but still does not show up in 
Firefox.

**Comment by todrobbins** [comment]
`/files/icon-source.svg` is actually a bitmap in an SVG. Do we have a vector of the nail in the circle so I can make the various favicon/touch icons requested in #68? Cheers! 🎩

**Comment by gvwilson** [comment]
That's weird.  I can send you the original SVG that the graphic designer gave us five years ago if you can give me an email address (can't attach to this thread because GitHub won't allow upload of SVG for some reason).

**Comment by gvwilson** [comment]
Trying to attach original SVG from the graphic designer via email...

**Comment by todrobbins** [comment]
todd.d.robbins@gmail.com

On Sunday, November 29, 2015, Greg Wilson notifications@github.com wrote:

> Trying to attach original SVG from the graphic designer via email...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/swcarpentry/website/issues/30#issuecomment-160538033.

## 

Tod Robbins
Digital Asset Manager, MLIS
todrobbins.com | @todrobbins http://www.twitter.com/#!/todrobbins
