### ISSUE TITLE
Blog post from the old "site" repo didn't make it into the new "website" repo

### ISSUE THREAD

**Issue by anelda** [swcarpentry/website-archive#300]
Hi all, how best could I bring this post into the new website repo https://github.com/swcarpentry/site/blob/master/blog/2015/10/jozihub-workshop.html?  Is there a script or something or could I just create it as a new file in the _posts/2015/10/ folder?

**Comment by gvwilson** [comment]
No script, I'm afraid - it'll need to be copied over manually.

**Comment by anelda** [comment]
Thanks! I've added the post through PR #301
