### ISSUE TITLE
"How can I attend a workshop" section needs work

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website-archive#310]
- An "announcements" list is referred to here: http://software-carpentry.org/faq/#how-attend-workshop but is not here: http://software-carpentry.org/join/ (and I've never heard of it).
- In that same paragraph we also say workshops are posted on twitter & our blog  but we don't post all workshops there.
- Should we note here that not all workshops are open to the public?

**Comment by gvwilson** [comment]
1. Reference to announcements list is gone.
2. Can you please suggest wording for 2nd and 3rd points, and I'll get into the website?
   Thanks,
   Greg
