### ISSUE TITLE
Instructor profile update form: Make it clear it's for current instructors only

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website-archive#335]
Instructors can submit a request for us to update their data on file via the link one the [join](http://software-carpentry.org/join/) page:

> If you are already an instructor and would like to let us know that you have moved, changed your email address, or are able to teach new lessons, please fill in this form to update your information.

However, probably around 10% of the submissions from this form are people thinking they are signing up for new instructor training.  Any suggestions on rewording this to make it clearer?

**Comment by gvwilson** [comment]
I don't know how to make it clearer than "if you are already an instructor" - @jduckles any suggestions?

**Comment by jduckles** [comment]
Dunno, bold that text?

I've always wondered why we don't just give our instructors a profile to login to where they can edit their own info. That would solve this problem. @gvwilson Can you tell me the reason the form works the way it does?

**Comment by maneesha** [comment]
I also think it's as clear as can be as is.   I just think we need to accept that there will always be a percentage of users who click without reading.  

About @jduckles  question:  We've just implemented a way for users to update their own data by logging in via github.  If they don't have a github account I think we can create a user/pw for them.  Can @gvwilson or @pbanaszkiewicz confirm this is ready  to roll out? 
Can we send an email to instructors letting them know about this?

**Comment by gvwilson** [comment]
People should be able to update their profiles directly in AMY now - 
I'll send an announcement next week after our current deployment's kinks 
are ironed out.  I'll close this issue.
