### ISSUE TITLE
github website repo link update in FAQ

### ISSUE THREAD

**Issue by creinkin** [swcarpentry/website-archive#338]
The FAQ section points to the old website repo url of htps://github.com/swcarpentry/site. This should probably be updated to /website per the redirect message on the /site page.

Submitted PR #337 to address this quick fix. Did not grep the whole repo for other instances. Can do that if desired, but for now just updating this one since I came across it while reading FAQs online.

**Comment by jduckles** [comment]
#337 closes this.
