### ISSUE TITLE
What mistakes would you like to see in an example video for instructor training?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#343]
We ask instructor trainees to create and critique short videos of themselves teaching (both stand-up and live coding). To prepare them for this, I would like to record a 90-second video of myself teaching; to ensure it's useful, I'd like to give viewers stuff to critique. So: what mistakes would you like the video to include in both content and presentation?  Things I've already thought of are:
- too much jargon
- ideas presented out of order
- lots of 'um' and 'er' (or using the word 'like' in every third breath, which is almost as bad as someone cracking their knuckles behind you during a thermodynamics exam when you're stuck on question 3, which has _nothing at all_ to do with the course material)

Please let me know what else you'd like to see by adding comments to this issue.  (I can't possibly live up to https://www.youtube.com/watch?v=FQjgsQ5G8ug&feature=youtu.be&t=35, but I'll give it my best shot...) Please also include ideas for both live coding and stand-and-deliver teaching.

**Comment by k8hertweck** [comment]
I'd like you to push the pace: type demo material quickly, and don't verbalize what you're typing.

**Comment by uiuc-cse** [comment]
Forget to turn off notifications from Slack or similar tools.

**Comment by liz-fernandez** [comment]
- Make a mistake during the live coding and skim through it - do not explain what happened

**Comment by IanHawke** [comment]
Talk at the screen and ignore the audience.

**Comment by justbennet** [comment]
Talking into the whiteboard is always good.  I was recently at a talk where the speaker had a lapel mic, and turning to write on the whiteboard also moved his mouth as far away from the mic as possible.

Criticize Excel as a crappy scientific tool.

**Comment by bast** [comment]
- Using "simple", "easy", "trivial", "can probably skip"
- Too small font
- Difficult colors
- Constantly switching between tabs and desktops
- Using custom aliases

**Comment by philrosenfield** [comment]
Ask a question and don't give any time for an answer. Perhaps say, "Any questions?" and immediately move on to another topic

**Comment by stevenkoenig** [comment]
- Jokes. Especially, if you are repeating them every second lesson or so.
- Stories. Even referencing unrelated stories ("that one time when some guy phoned you to sell lawnmower insurance") should be avoided completely. Related stories can be very insightful, but should not be repeated more than once per semester.
- Quickly answer an uber-important e-mail you just received on your smartphone or just doing anything unrelated with your smartphone.
- Jumping over interesting stuff, because it is not relevant for the exam.

**Comment by snacktavish** [comment]
- Make fun of Windows.
- Use aliases as shortcuts in bash

**Comment by mfoos** [comment]
I was reminded by "make fun of windows": Forgetting/failing to inform students with Windows boxes that their terminal is different!

**Comment by mikej888** [comment]
Telling Word users that Git really only works best with plain-text files and they'd best switch from using Word.

**Comment by mfoos** [comment]
Oh, one more: Having "toy" examples that run forever and then students don't need to use the output. I think this can happen from testing on a different system/number of cores than it will ultimately happen on. This could be DC-specific, it's been a while since I've done SWC

**Comment by codersquid** [comment]
Post a link to the item that resolves this issue! https://youtu.be/-ApVt04rB4U

**Comment by apawlik** [comment]
You've already done it but: engage in an advanced discussion with 20% of the audience who already know everything that is in the curriculum and are clearly as bored with the module as yourself (the teacher). Show the rest of the class what a chore it is having to teach such trivial stuff to a bunch of people that shouldn't be there.

**Comment by yabellini** [comment]
The new link for the video with subtitles in English and Spanish: https://www.youtube.com/watch?v=jxgMVwQamO0

**Comment by maneesha** [comment]
Thanks @yabellini for doing this! 
This video is used for our instructor training program, which has since moved to its own repo.  I've made a note about this in [that repo](https://github.com/carpentries/instructor-training/issues/1243).  We'll keep this issue closed and follow up in the instructor training repo.
