### ISSUE TITLE
What studies do you cite when talking about open access?

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#368]
Questions about the impact of open access come up pretty often when I'm teaching Git, so I am looking for pointers to well-founded studies (not opinion pieces) that I can cite as answers (and to dispel myths). For example, [1] seems to show that making data openly accessible does _not_ lead to you being scooped, while [2,3,4] shows that open access publications have a higher citation count than closed access equivalents.
1. http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002432
2. https://dspace.lboro.ac.uk/dspace-jspui/bitstream/2134/4089/1/Thesis%20MN.pdf
3. https://peerj.com/articles/175/
4. https://infoscience.epfl.ch/record/206184/files/Vandewalle12.pdf

**Comment by npch** [comment]
I also cite:
- http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0000308

There may also be some interesting reading coming out of neuroscience as they are further ahead in the "identify everything so we can actually measure it" initiatives - papers by Melissa Haendel and Anita Bandrowski look like they're close to getting to being able to do large scale studies of the literature.

Will be very interested to see what else people use!

**Comment by jlehtoma** [comment]
A bit older one:
1. http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.0040157

**Comment by karawoo** [comment]
We pulled together a number of sources for this manuscript on the benefits of open research: https://figshare.com/articles/The_open_research_value_proposition_How_sharing_can_help_researchers_succeed/1619902

**Comment by rossmounce** [comment]
Some of the OpenCon community published this review recently: http://f1000research.com/articles/5-632/v1
_The academic, economic and societal impacts of Open Access: an evidence-based review_

Good overview of the vast swathe of published studies on OA citation advantage amongst other things. Citations aren't the be all and end all though :wink:

**Comment by rossmounce** [comment]
This is also a MUST CITE for me: _Willingness to share research data is related to the strength of the evidence and the quality of reporting of statistical results_ http://dx.plos.org/10.1371/journal.pone.0026828

**Comment by libcce** [comment]
@aaccomazzi @ehenneken and Kurtz from the @adsabs have done some work in this area: http://arxiv.org/abs/1111.3618

**Comment by arokem** [comment]
I have anecdotal evidence that releasing data under a permissive license, and making it really easy to access (e.g. through software), can lead to your work _not_ being cited, possibly because it makes your contribution "invisible". Something to think about.

**Comment by jduckles** [comment]
Closing.
