### ISSUE TITLE
Inconsistency in the number of recommended instructor / helpers

### ISSUE THREAD

**Issue by apawlik** [swcarpentry/website-archive#370]
As noted by one of the participants of the SSI Instructor Training:
_What is the recommended number of instructors / helpers? The "FAQ" page says 2 instructors and 2-3 helpers for 40 learners, the "Workshop Operations" page says 2-3 instructors for 20-50 learners and (at least) 1 helper for every 10 learners, while the "Software Carpentry: Lessons Learned" paper says 1 helper for every 8 learners._

**Comment by SpacedGirl** [comment]
Wow. I'm confused just reading and they were found in different places. Maybe an overall chart with different # of learners vs. instructors and helpers would rectify the current situation and keep it from occurring again or when wanting to update.

**Comment by apawlik** [comment]
Thanks @SpacedGirl . Not sure what you mean about the chart? The thing is that the recommendations should be consistent. Normally we say 2 instructors (can be more but never one). With the helpers, I would say that the recommended ratio is 1 helper per 6-8 learners. Though I'd add a disclaimer that this is not always feasible but going to a ratio lower than 1/10 is also not recommended. Does this make sense or am I overcomplicating that?

**Comment by SpacedGirl** [comment]
Not sure what was taken from my statements and haven't fully read again. [nevermind....just read here]. 

The chart was really a table. I was thinking of putting all current thinking in terms of student counts vs instructors and helpers in a single easy to read table and use that whenever necessary. Also, if a new convention/thinking arises; remember to change the table and update where ever it's used.

One of points that I haven't been explicit about is that it's easier reading in a table than through paragraph writing.

**Comment by jotasprout** [comment]
If there is an agreed-upon ratio, I'm happy to make the changes in the places mentioned by @apawlik on May 5.

**Comment by jduckles** [comment]
@jotasprout We usually say 1 helper for every 10 learners and you can include the instructor that is not actively instructing in that count. So 10 learners, you can handle with just the two instructors. 20 you need one helper and 30, 2 helpers, 40 (our max suggested) you need 3. Please do submit a PR for the changes in those two places mentioned. Thx.

**Comment by jotasprout** [comment]
Got it. I'll get on it.
