### ISSUE TITLE
Additions to instructor and lead instructor checklist

### ISSUE THREAD

**Issue by carpenterbennet** [swcarpentry/website-archive#375]
Please add an item to the instructor's checklist that indicates that the not currently active instructors should sit at the back and not try to take an active role.  The helpers roles are different, and not currently active instructors should resist the urge to help unless there is clear need for it.  This is covered in the verbal portion of instructor training, but it didn't come across to me as a hard rule and expected behavior, but rather as one example of many.  It will help to prevent future confusion if it is added as a rule to the checklist.  At least for the workshop in which I was involved, the instructors were also not to act as helpers.

Please add to the item for lead instructors to be sure to go over with the other instructors prior to the workshop what the expected activity level should be for the not currently active instructors, and any other things that might help.  This will help alleviate any inadvertant misunderstandings, particularly for any new instructors.  This would also be the place to agree if some other arrangement among instructors could be agreed if the basic guidelines are to be deviated from.

I think this is particularly important when there are first-time or inexperienced instructors.  Software Carpentry teaching is possibly not like other teaching venues, and it is easy for people who have experience from other venues to bring with them habits that may not be appropriate in SWC.  Clearly set expectations are a good deal easier to meet.

I might make things more clear if the term 'coinstructor' is not used, as that is susceptible to misinterpretation.  Rather, it seems, instructors 'take turns' from one lesson to the next.

**Comment by gvwilson** [comment]
Thanks for the detailed PR - cross-posted to https://github.com/swcarpentry/instructor-training/issues/176 so that it goes into training as well.
