### ISSUE TITLE
update steering committee tags

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/website-archive#377]
The steering committee tags should be updated on the team member page. The past member's tags can be updated to reflect past membership on the committee, some roles need to be updated, and  tags should be added for the new members.

**Comment by gvwilson** [comment]
Can you please submit a PR with the fixes?

**Comment by raynamharris** [comment]
Sure thing.... which file(s) should I edit?

**Comment by gvwilson** [comment]
swcarpentry/website, the gh-pages branch, _includes/people/*.html - thanks.

**Comment by raynamharris** [comment]
Okay, I think I've addressed all the updates in https://github.com/swcarpentry/website/pull/485
