### ISSUE TITLE
No pins on map

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/website-archive#387]
Chrome:

![screenshot from 2016-05-16 19-17-02](https://cloud.githubusercontent.com/assets/1506457/15299147/f64d5564-1b9a-11e6-8208-d1cb85892e92.png)

Firefox:

![screenshot from 2016-05-16 19-17-43](https://cloud.githubusercontent.com/assets/1506457/15299159/0540f72e-1b9b-11e6-84c0-ab4b7e23b7cd.png)

**Comment by maneesha** [comment]
I think this happens every few months.  Did we ever figure out what was going on?

**Comment by raynamharris** [comment]
@maneesha It was working at the in person steering committee meeting. I just noticed yesterday that it wasn't working.

**Comment by gvwilson** [comment]
@rgaiacs @pbanaszkiewicz is anyone working to fix this?
