### ISSUE TITLE
Use _data files for persons and projects to remove need for preprocessor

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#39]
Via @andreabedini: instead of storing HTML snippets in _includes/people and _includes/project, we can put stuff in _data and refer to it directly.  E.g., the file `_data/people/wilson.g.yaml` could include:

```
id: wilson.g
name: Greg Wilson
biography: '[Greg Wilson](http://www.third-bit.com) started the Software Carpentry
  project in 1998. He has been a professional software developer, an author, and a
  university professor. Greg received his PhD in Computer Science from the University
  of Edinburgh in 1993.'
```

The data can be accessed as `site.data.people.wilsong`. (The dot gets eaten, because `site.data.people.wilson.g` would mean the wrong thing, which is why the ID is stored in the `id` field.) Generating the current

```
<p id="wilson.g" data-toggle="tooltip" title="<img src='{{page.root}}/img/people/wilson.g.jpg' alt='Greg Wilson' />">
    <a href="http://www.third-bit.com" class="person">Greg Wilson</a>
    started the Software Carpentry project in 1998. He has been a
    professional software developer, an author, and a university
    professor. Greg received his PhD in Computer Science from the
    University of Edinburgh in 1993.
    <br/>
    <strong>Executive Director</strong>
</p>
```

should be easy, and fields can be added for special roles (Executive Director, Steering Committee, maintainer).

**Comment by djacquel** [comment]
As advised in https://github.com/swcarpentry/website/issues/10#issuecomment-160475248 , it can be useful to have people and projects datas in collections not in datas files.
This allows to automatically create pages for each elements, which can be interesting for authors pages with bio and posts.

**Comment by andreabedini** [comment]
@djacquel I considered using collections but I couldn't find a way to refer to specific items needed for few pages.

``` diff
   <div class="small-4 columns">
     <h4>Executive Director</h4>
-    {% include people/duckles.jonah.html %}
+    {{ site.data.people['duckles_jonah'].content }}
   </div>
```

you can't do `site.data.people['duckles_jonah']`. There might be a solution (I am excluding iterating and filtering which won't scale well) but I couldn't find it. Perhaps jekyll has a 'url-of' helper somewhere.

EDIT: `url-of` is not what we would need. We need to be able to index in the collection, just like above.

**Comment by djacquel** [comment]
@andreabedini 

Until you don't need to generate a page for each People or for projects, putting them in data files is ok.

Concerning the biography field :

  1 - Use explicit multi-line delimiter

```
biography: >
   Any line
   you want
   here
```

This avoid yaml parser to break when it finds illegal characters like ":"

2 - In order to parser markdown enclosed in html tags, add in **_config.yml**

To parse

```
biography: >
    # No problem
    <p>**problem**</p>
```

```
kramdown:
  parse_span_html: true
  parse_block_html: true
```

**Note**: the include problem with collections can be resolved

```
{% include people-content.html id=duckles.jonah %}
```

**_includes/people-content.html**

```
{% assign p = site.people | where: 'id', include.id %}{{ p.content }}
```

**Comment by andreabedini** [comment]
sounds good @djacquel. I'll give it a try to this approach too. @gvwilson I understand this is not an urgent issue right?

**Comment by gvwilson** [comment]
Correct, this is not a priority for our 1.0 release - please see 
https://github.com/swcarpentry/website/milestones/Version%201.0 for the 
things we need to close so that we can switch over.
