### ISSUE TITLE
Semi-broken links in host checklist

### ISSUE THREAD

**Issue by omsai** [swcarpentry/website-archive#392]
Edit: Updated to reflect that all `#host_...` links are semi-broken.

Steps to reproduce:
1. Open http://software-carpentry.org/checklists/host/
2. Click on any link with `#hosts_...` in the link name (e.g. "cost of running a workshop")

Result:  The link takes you the top of the page http://software-carpentry.org/workshops/operations/ instead of the section.

Expected result: The link should probably point to the section within the page.

For "cost of running a workshop", not sure if the link on the [operations page](https://github.com/swcarpentry/website/blob/gh-pages/pages/workshops_operations.html#L219) should be changed from `id=cost` to `id=host_cost` or if the link on the [host page](https://github.com/swcarpentry/website/blob/gh-pages/pages/checklists_host.html#L54) should be changed from `#host_cost` to `#cost`.  From looking at the git histories of both pages, it seems the section links were never working.

**Comment by omsai** [comment]
Or maybe costs should point to this page? http://software-carpentry.org/workshops/request/

**Comment by gvwilson** [comment]
Thanks Pariksheet - good catch.

**Comment by jduckles** [comment]
Fixed by f39313968412c
