### ISSUE TITLE
FAQ links broken

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website-archive#394]
From an email sent to me:

> in the question 'How can I become an instructor myself?' in the FAQ on
> the swcarpentry website, the two links 'free online training course' and
> 'course blog' are broken (or, rather, point back to the FAQ itself).

**Comment by derekisensee** [comment]
took a look at this, should be fixed. faqFix branch.

**Comment by gvwilson** [comment]
Can you please give us a link to the faqFix branch?  Or alternatively submit a PR?
Thanks.

**Comment by derekisensee** [comment]
sent!
