### ISSUE TITLE
"Our members" and "Our team" are different

### ISSUE THREAD

**Issue by btel** [swcarpentry/website-archive#410]
The table of members in https://github.com/swcarpentry/website/blob/gh-pages/pages/scf_members.html is different from the one on "Our team" page. Is it intentional? 

The governance file says that:

> ```
> 2.  <a name="membership"></a>
> The Membership is made up of:
> 
> a.  Every qualified instructor who has taught at least twice in the
>     past two calendar years.
> 
> b.  Anyone who has done 30 days or more work for the SCF in the past
>     calendar year.
> 
> c.  Anyone who has, in the opinion of the Steering Committee, made
>     a significant contribution in the past year.
> 
> Members elect the Steering Committee, and may also seek election to
> it.
> ```

Many instructors from "Our team" who fulfill condition (a) (myself included) are not listed on "Our members" page.

**Comment by gvwilson** [comment]
I believe "Our Members" is only updated annually, just prior to our election, but I'll check.

**Comment by gvwilson** [comment]
Yes - "Our Team" is everyone who is a qualified instructor or staff member, where "Our Members" are people who've been active recently enough to vote.
