### ISSUE TITLE
Some workshops on "Past workshops" are misplaced

### ISSUE THREAD

**Issue by btel** [swcarpentry/website-archive#411]
Some of the workshops on [Past workshops](http://software-carpentry.org/workshops/past/) page are misplaced. In particular, these workshops appear in Asia:

[Elizabeth City State University: Jun 08-09, 2016](https://shwina.github.io/2016-06-08-ECSU/)
[Minneapolis, Minnesota: Jul 30-31, 2015](http://www.datacarpentry.org/2015-07-30-ASPB/)
[UC Davis](http://www.datacarpentry.org/2015-09-22-UCDavis/)

This gives us a global reach, but it may not be exactly true...

**Comment by gvwilson** [comment]
Thanks, I'll look in the database for these.

**Comment by maneesha** [comment]
These were all due just to typos in the location for lat/lon.  They have been fixed. 
Thanks @btel  for catching them.
