### ISSUE TITLE
Create new checklist for maintainers

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#415]
Guidelines for being a maintainer should be in a checklist, along with guidelines for running workshops. Should include some of https://blog.jessfraz.com/post/the-art-of-closing/

**Comment by butterflyskip** [comment]
Hey,

Newbie here, anything I can do?  Will need breadcrumbs and a wee bit of hand-holding to get off the starting block

Txs

**Comment by weaverbel** [comment]
Maintainer roles now addressed through Carpentries community page so I am closing this now.
