### ISSUE TITLE
Calendar points at old web site

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#43]
The calendar of upcoming events on `/workshops/` currently points at the `.ics` file on the old website. We need to point at the `.ics` we're generating, then test that it all actually works.

**Comment by andreabedini** [comment]
I don't understand. Workshops are already on Google Calendar, right? Doesn't it provide a ICS? Why are we generating a ICS ourselves?

**Comment by gvwilson** [comment]
The Google Calendar gets its data from our .ics file - we don't add 
workshops manually.

**Comment by andreabedini** [comment]
@gvwilson got it, it was the other way around.
