### ISSUE TITLE
HTTPS broken

### ISSUE THREAD

**Issue by dopplershift** [swcarpentry/website-archive#455]
I'm not sure if https is something you want to support (though the basic website _does_ respond to https), but using https causes all of the formatting to be broken (I think the CSS just doesn't show up). With https:

![screen shot 2016-07-20 at 1 59 32 pm](https://cloud.githubusercontent.com/assets/221526/17000964/4756237c-4e82-11e6-8897-24829a6ea440.png)

On http:

![screen shot 2016-07-20 at 1 59 58 pm](https://cloud.githubusercontent.com/assets/221526/17000970/501a3ac0-4e82-11e6-8c9c-9a3eeda2a72d.png)

**Comment by gvwilson** [comment]
Should now be fixed - please check and let us know.

**Comment by dopplershift** [comment]
Looks fine to me now. Thanks!
