### ISSUE TITLE
Listing DC workshops

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/website-archive#461]
FYI - The SWC /workshops/ page is currently listing both SWC and DC workshops. Not sure if this is intentional, but DC is not cross-listing SWC workshops on our page.

@tracykteal @maneesha @gvwilson

**Comment by maneesha** [comment]
I am fine either way. 
I do think that if we're listing all workshops like on the SWC page we should have tags indicating what kind (maybe next to the country flag?)

Note we also need to decide what to do about Library Carpentry workshops (see https://github.com/swcarpentry/amy/issues/920)

@jduckes should also weigh in.

**Comment by tracykteal** [comment]
I think it should just be SWC workshops. I thought we had set things up this way previously. Maybe it got reverted in a recent commit. @gvwilson?

Some library folks are working through SWC now and some through DC. I think we just leave them listed as SWC or DC for now, depending on how they're booked.

**Comment by gvwilson** [comment]
The last change was 2016-01-09, when the tags "SWC,DC,TTT" were added to the line in the Makefile that fetches data from AMY.  I can change that to "SWC,TTT" if that's desired - @jduckles?

**Comment by jduckles** [comment]
@gvwilson yes please just go down to SWC. The TTT being included has caused more confusion than it has helped as it shows closed trainings, can we cut that one from the schedule too?

**Comment by gvwilson** [comment]
See #468.  (Also filed #469.)

**Comment by pbanaszkiewicz** [comment]
Listing LC/DC/SWC-only published events is currently available from AMY, for example see https://amy.software-carpentry.org/api/v1/events/published/?tag=LC

**Comment by tracykteal** [comment]
Yes, thanks @pbanaszkiewicz! We're using those tags for publishing to the website.

**Comment by ErinBecker** [comment]
@gvwilson Not sure why this was closed. From my end it still looks like DC workshops are being cross-posted on the SWC /workshops/ page. See for example University of Rhode Island Aug 29th and University of Edinburgh Aug 22nd.

**Comment by gvwilson** [comment]
Should be closed when #468 is merged.

**Comment by ErinBecker** [comment]
Thanks @gvwilson

**Comment by gvwilson** [comment]
@ErinBecker can you please check (and close this if it's working)? thx.

**Comment by ErinBecker** [comment]
@gvwilson Looks good.
