### ISSUE TITLE
Outdated fee information in linked slides

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/website-archive#491]
In /lessons/ "Hosting a Workshop" slideshow, fee information is out of date.

**Comment by gvwilson** [comment]
We are discussing retiring these slides entirely, since nobody has been 
maintaining them.  (But if you'd like to be maintainer...)

**Comment by ErinBecker** [comment]
Ha! Not volunteering.

**Comment by jduckles** [comment]
Fixed by #492
