### ISSUE TITLE
linking instructor notes on lessons page

### ISSUE THREAD

**Issue by ChristinaLK** [swcarpentry/website-archive#510]
Suggestion: replace the links to the "reference" for each lesson with a link to the instructor notes
(this is on software-carpentry.org/lessons/)

Rationale: The reference page is linked directly in the menu on the lesson pages, while the instructor notes are not, making it harder to find.  If people are mostly finding the lessons through the software-carpentry.org/lessons page, this makes the notes more prominent. 

I have a PR ready to go, if people think this is a good idea.

**Comment by maneesha** [comment]
Would this replace the content of the "Reference" page or combine it with instructor notes?

**Comment by raynamharris** [comment]
Providing a direct link to the instructor notes seems like a great idea to me!

**Comment by ChristinaLK** [comment]
I was thinking replace (just to keep there from being _too_ many icons), but could add instead.

**Comment by maneesha** [comment]
I think I may not have been clear.  So would the existing content of the "Reference" page disappear or would it be integrated in to the Instructor Notes?

I do want to make the Notes easier to find but don't want to confuse people if the Reference content disappears.

**Comment by ChristinaLK** [comment]
Ah, leave the content of both pages, but instead of linking directly to the reference from software-carpentry.org/lessons, link to the instructors notes instead.

**Comment by lexnederbragt** [comment]
Why not have both?

**Comment by ChristinaLK** [comment]
We could have both, it just ends up being a lot of icons.  But that's probably okay.

**Comment by jduckles** [comment]
We do have both, when you click the **Site** link you get the instructor notes. Am I missing something?

**Comment by lexnederbragt** [comment]
The **Site** one links to the main page of the lesson, e.g. http://swcarpentry.github.io/shell-novice/. We propose to add a column with a direct link to the instructor notes, e.g. http://swcarpentry.github.io/shell-novice/guide/.

**Comment by ChristinaLK** [comment]
Sorry all, THIS is what I meant: http://pages.cs.wisc.edu/~ckoch5/notes_column.jpg

Should be REALLY easy - the only thing I can't figure out is how to add a nice icon to the set we already have.

**Comment by gvwilson** [comment]
Look in assets/fonts/svg-files-for-custom-font/*.svg for the available 
icons - if you then add a line like:

> <a href="URL-TO-LINK-TO" target="_blank" class="icon-eye" 
> title="LINK-TITLE"></a>

but replace 'icon-eye' with 'icon-whatever' (where 'whatever' is one of 
the filenames from the SVG font directory), it should just work.

**Comment by jduckles** [comment]
Closing as outdated.
