### ISSUE TITLE
"Our Team" page should show only active instructors

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website-archive#526]
I often get requests for workshops and they ask for local instructors - understandably, to keep costs down.
I can't always get them local instructors -- but they look at this page http://software-carpentry.org/team/  and see there _are_ instructors in their area.  However, what someone looking at our website does not know is they have not taught with us in a couple of years and have not responded to any emails I've sent out.

Maybe active = members + badged in last 12 months?

**Comment by jduckles** [comment]
Should this be an AMY issue first to get a feed of "active" instructors?

**Comment by jduckles** [comment]
Closing and adding an issue to Amy to define "Active" flag on instructors.

**Comment by jduckles** [comment]
Moved this to an AMY issue: https://github.com/swcarpentry/amy/issues/1209
