### ISSUE TITLE
Apply for Instructor Training

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/website-archive#543]
Can we have "Apply for Instructor Training" linking to https://amy.software-carpentry.org/workshops/request_training/ from the header?

**Comment by gvwilson** [comment]
Sure - please PR.

**Comment by rgaiacs** [comment]
I think this is out of date based on

> Registration for the Fall 2016 training courses is now closed, but we are still accepting applications for subsequent courses. If you would like to apply, or are taking the course through one of our partner organizations and have been asked to provide information, please fill in this form.
