### ISSUE TITLE
Links to discussion etherpads broken

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/website-archive#587]
@ChristinaLK The two links to the discussion etherpad from the mentoring committee page are broken. Should link to http://pad.software-carpentry.org/instructor-discussion

**Comment by jduckles** [comment]
@ErinBecker Can you tell me the page where the link is broken. I'm not sure which one you're referring to. Thx.

**Comment by ErinBecker** [comment]
@jduckles Sorry - was in a rush earlier. The page is /join/subcom/mentoring/

This para: 
Hosting discussion sessions: If you have taught at at least 2 workshops and enjoy discussing teaching and Software Carpentry, feel free to sign up as a co-host for our regularly hosted discussion sessions, found at this etherpad.

And this: 
hosting one or two instructor discussion sessions per month; see the discussion etherpads

**Comment by jduckles** [comment]
Should be fixed. Note: the website only updates every 30min, so it might take a bit before the fix is live)
