### ISSUE TITLE
Generate .ics file using Jekyll

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#59]
We should generate the .ics calendar file used to show upcoming workshops using Jekyll. http://software-carpentry.org/workshops.ics can be used as a starting point. Cf. #43.

**Comment by gvwilson** [comment]
Using method from @djacquel's http://stackoverflow.com/questions/32894339/calculating-with-time-in-jekyll (m'gawd, the hoops you have to jump through to add a day to a date in Jekyll...)

**Comment by pbanaszkiewicz** [comment]
> (m'gawd, the hoops you have to jump through to add a day to a date in Jekyll...)

Apparently `Post.date` is a string or something, but certainly not a Ruby's `Time` object…
