### ISSUE TITLE
workshop map not working

### ISSUE THREAD

**Issue by maneesha** [swcarpentry/website-archive#616]
From a community member: 

> It appears the map showing upcoming workshops is not loading on https://software-carpentry.org/workshops/. The responsible element (id = "map_canvas") just results in a large white space above the future workshops table ...
> 
> 
> Occurs on Ubuntu 16.04, Firefox and Chrome.
> 

I've checked & the problem occurs across operating systems and browsers.

**Comment by rgaiacs** [comment]
Looks like that it is caused by

> Mixed Content: The page at 'https://software-carpentry.org/workshops/' was loaded over HTTPS, but requested an insecure script 'http://jawj.github.io/OverlappingMarkerSpiderfier/bin/oms.min.js'. This request has been blocked; the content must be served over HTTPS.

And looks that there is some issue wit keys:

> util.js:211 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

**Comment by katrinleinweber** [comment]
@rgaiacs @jduckles: I wanted to make some nice screenshots, but there is a recurrance of this problem from another error source. My Firefox console tells me: `You have exceeded your request quota for this API. See https://developers.google.com/maps/documentation/javascript/error-messages#api-key-and-billing-errors`.

[![grafik](https://user-images.githubusercontent.com/9948149/43446553-7c3397b8-94a9-11e8-80aa-c3dc6b7b2990.png)](https://software-carpentry.org/workshops/past/)

"Google Maps can not be properly loaded on this site." is the pop-up's translation.

**Comment by katrinleinweber** [comment]
If paying is not an option, how about converting the annotions to OpenStreetMap. I haven't worked on including such a map widget in a website though, but there seem to be [some options for that](https://wiki.openstreetmap.org/wiki/KML).

**Comment by rgaiacs** [comment]
@katrinleinweber Thanks for the comment. Staff are investigating it, please see https://github.com/swcarpentry/amy/issues/1248.

**Comment by jduckles** [comment]
See https://github.com/swcarpentry/website/issues/1062 

Google MapsAPI has some new structure where you get $200 credit, then have to have a Credit Card on file which is designed to keep Google shareholders happy or something. Happy to have some help on the JS front if you're keen @katrinleinweber Over at #1062 I'm thinking through options.
