### ISSUE TITLE
Twitter list of instructors

### ISSUE THREAD

**Issue by jduckles** [swcarpentry/website-archive#635]
We collect twitter handles using AMY, it would be nice to have a twitter list that is regularly updated so people can follow all SWC/DC instructors via one twitter list.

**Comment by raynamharris** [comment]
While not exhaustive, @maneesha maintains this list https://twitter.com/maneeshasane/lists/swc-dc

**Comment by jduckles** [comment]
Done! https://twitter.com/swcarpentry/lists/swc-instructors
