### ISSUE TITLE
Odd logo display on Android

### ISSUE THREAD

**Issue by lgatto** [swcarpentry/website-archive#65]
Following up from [these tweets](https://twitter.com/gvwilson/status/670674713618849792), here is was is observed on an Android phone, using firefox and default browser.

![cu5u_jywoae0bib](https://cloud.githubusercontent.com/assets/384198/11454514/208001ec-9626-11e5-87bb-315e65da668f.jpg)

**Comment by jduckles** [comment]
It is coming from the `class="icon-tree"` in 

```
<h1 class="show-for-small-only"><a href="http://dev.software-carpentry.org" class="icon-tree"> Software Carpentry</a></h1>
```

**Comment by gvwilson** [comment]
OK, so it's a default fallback built into FR - I'll try to figure it 
out.  Still also trying to figure out why the wrong favicon shows up...

**Comment by djacquel** [comment]
What is the desired behaviour ?

**Comment by gvwilson** [comment]
Easiest is to make the logo disappear entirely when there's not space to display it - we've still got the text title "Software Carpentry". @todrobbins has done that in #68, and is going to upload fresh versions of the other-sized icon files once he gets a decent SVG to work from.
