### ISSUE TITLE
Community roles

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/website-archive#650]
I was talking with a friend and he points me out to http://www.astropy.org/team.html. I really liked it and I think that we should have something like it. I know that we list the lesson maintainers at https://software-carpentry.org/lessons/ and a list of other key contributors at https://github.com/swcarpentry/board/tree/master/subcommittees but a much visible place would be great.

**Comment by ErinBecker** [comment]
Thanks @rgaiacs for this! I also really like the page you linked and would love to have something similar for the SWC/DC websites. I can put it on my to-do list, but if you know anyone in the community who is interested in putting something like this together (including yourself), it might get done sooner than I can tackle it.

**Comment by rgaiacs** [comment]
https://github.com/swcarpentry/board/issues/185 is related with this one.

**Comment by jduckles** [comment]
Tagging @weaverbel because this kind of thing is now in her purview.

**Comment by weaverbel** [comment]
I think these are now addressed by our Carpentries team page and our community page which lists roles so I am closing this for now.
