### ISSUE TITLE
Past workshops map not working

### ISSUE THREAD

**Issue by DamienIrving** [swcarpentry/website-archive#658]
The map of past workshops is missing when I view the following page:
https://software-carpentry.org/workshops/past/

Perhaps this is a similar problem to that discussed in #616?

**Comment by maneesha** [comment]
Just came to file this issue.... still not working.

**Comment by jduckles** [comment]
It appears to be an errant UNICODE control character [1] (U+0009) making the JSON parser angry.

I've submitted a PR https://github.com/JNandez/2017-01-16-ccg-unam/pull/1 to fix it upstream.

[1] - https://r12a.github.io/uniview/?charlist=LCG-Aula%091-2%2C%20#title

**Comment by jduckles** [comment]
Should be working now:

https://software-carpentry.org/workshops/past/
