### ISSUE TITLE
nbdiff.org domain expired

### ISSUE THREAD

**Issue by joelostblom** [swcarpentry/website-archive#660]
Just a heads up that the domain nbdiff.org for the jupyter notebook diff tool, referenced on the ["Help Wanted" page](https://software-carpentry.org/join/help/), has expired.

**Comment by rgaiacs** [comment]
@joelostblom Thanks. I reported this upstream. We will wait a few days to take any action.

**Comment by tarmstrong** [comment]
Hey folks - I let the domain lapse since the project isn't active any more and the [nbdime](https://github.com/jupyter/nbdime) project seems to have more traction. Maybe it would be better to update the "Help Wanted" page to point to that project instead?
