### ISSUE TITLE
Dead link on FAQ

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/website-archive#661]
https://software-carpentry.org/faq/#creating-lesson points to a slideshow at https://github.com/swcarpentry/slideshows/creating-lesson/index.html which leads to a 404...

**Comment by katyhuff** [comment]
Related: all subheadings of scf in the faq question related to fees no longer lead to their intended locations. 

Administration Fee links to : https://software-carpentry.org/scf/workshops.html
Membership also links to : https://software-carpentry.org/scf/membership.html

They're supposed to go to individual pages, but default to the scf main page.

**Comment by jduckles** [comment]
@weaverbel could you investigate this one.

**Comment by jduckles** [comment]
Closing as the FAQ is moving to our helpdesk tool soon.

**Comment by weaverbel** [comment]
I fixed them in both places anyway! I hate for stuff to be wrong.
