### ISSUE TITLE
Have site and reference before repo on lessons page

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/website-archive#67]
The table with the different lessens on http://dev.software-carpentry.org/lessons/ has the columns with links in the order repo-site-reference-maintainers. I suspect many visitors will be most interested in the site, not so much the repo. Perhaps change the order of the links to site-reference-repo-maintainers?

**Comment by gvwilson** [comment]
Agreed, but I'd like to find icons for "site", "repo", and "reference 
guide" instead of repeating the words - any suggestions?

**Comment by lexnederbragt** [comment]
What about:
- 'site' the mini-SWC logo
- 'repo' the github octocat logo
- 'reference' an open book icon

But then perhaps add a table header with 'topic, site, reference, repo, maintainers' as plain text?

**Comment by gvwilson** [comment]
@lexnederbragt please see #74.
