### ISSUE TITLE
Checklists: add for host, check with venue for participant list needs

### ISSUE THREAD

**Issue by lexnederbragt** [swcarpentry/website-archive#685]
Sometimes the venue needs the list of participants for their visitor registration system. Add to the checklist for the host that they 

1. check with the venue whether this is needed
2. provide the list at the agreed upon time

(I would have submitted a PR but the checklists are in html only (right?) and I am not very good at writing hmtl)

**Comment by jduckles** [comment]
I think we're going to take a run at the FAQs and checklists pretty soon to streamline them. Tagging @weaverbel so she's aware, but also closing for now.
