### ISSUE TITLE
Strange wording in CoC footer

### ISSUE THREAD

**Issue by arokem** [swcarpentry/website-archive#690]
(here: https://software-carpentry.org/conduct/)

"This code of conduct is an adaptation of the one used by the Software Carpentry Foundation" 

Isn't this the very CoC used by the SCF? What's the "adaptation"?

**Comment by k8hertweck** [comment]
Ah, good catch. The latest update to the CoC (in late 2017) was a joint effort from Software Carpentry and Data Carpentry. I suspect the update used the language from the DC website, which was then copied to the SWC website following approval by the SWC steering committee. It may be clearer to state "This code of conduct is a modified version of that used by PyCon...", which simplifies the history but is much more cogent. @karinlag is the steering committee liaison to the subcommittee who manages the CoC and can confirm (and possibly approve a minor wording change for clarity?)

**Comment by ErinBecker** [comment]
@arokem @k8hertweck Yes, good catch. The language should be modified to what Kate suggested. 

@pbarmby is the Policy subcommittee chair - could you please approve the language modification for the SWC website?

**Comment by PBarmby** [comment]
Thanks for the catch @arokem. The language modification - dropping " is an adaptation of the one used by the Software Carpentry Foundation" is fine with me.

**Comment by karinlag** [comment]
I do believe we agreed on a change mechanism when we set up the policy committee? I cannot find the initial docs for how the policy committee should work, and how changes to the CoC should be introduced. Maybe @PBarmby or @jduckles could dig those out? 

If we don't have a change mechanism set up, we should figure that part out first. I do not believe that I can or should approve something like this myself, even if it is of such a technical nature.

**Comment by ErinBecker** [comment]
@karinlag This is really not a change to the policy, just a correction in the attribution. I think this change can be made easily and without complication.

**Comment by k8hertweck** [comment]
Thanks @ErinBecker for the quick resolution.

@karinlag I concur with Erin's earlier statement that this is an issue with attribution, not the policy itself. I will leave it to the committee to confirm their documentation for how changes in policy and/or procedures are changed.
