### ISSUE TITLE
Not collapsing to a single column as it should

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#70]
@jiffyclub reports that the site does not collapse to a single column on mobile as it should (see screenshots). The http://datacarpentry.org site _does_ collapse, so this is almost certainly something that @gvwilson broke during the conversion (using fixed columns for layout instead of using the template properly).
![img_9518](https://cloud.githubusercontent.com/assets/911566/11465399/502644e6-9730-11e5-8f0a-ed558c59005a.PNG)
![img_9519](https://cloud.githubusercontent.com/assets/911566/11465400/5029dc50-9730-11e5-9688-7cc7bfe9145d.PNG)
![img_9520](https://cloud.githubusercontent.com/assets/911566/11465401/502fd01a-9730-11e5-8c6e-95d516d553b5.PNG)
![img_9521](https://cloud.githubusercontent.com/assets/911566/11465402/50304d9c-9730-11e5-8bbe-b91db3383f87.PNG)

**Comment by jiffyclub** [comment]
Note also that the footer is jumbled in the first screenshot here. It still looks like that even with the new changes.

**Comment by andreabedini** [comment]
Here's my solution to the footer problem.
