### ISSUE TITLE
including python gapminder in lessons

### ISSUE THREAD

**Issue by ErinBecker** [swcarpentry/website-archive#704]
Interesting conversation today with an instructor about the [python gapminder lesson](http://swcarpentry.github.io/python-novice-gapminder/). It appears to be pretty far along in development - do we have a date at which we'll be advertising this on the lessons page?

**Comment by k8hertweck** [comment]
Thanks for the issue; we're happy that @ntmoore has accepted the maintainer position for this lesson and would be interested to hear his thoughts. Clearly, folks have been continuing to use the lesson anyway but it would be nice to clarify its status for the community.

A related issue is whether we will be removing other lessons as "supported." I'll bring this general issue to the SC at our next meeting.

**Comment by ntmoore** [comment]
I worked through most of the old pull requests in March/ early April.  I taught the Gapminder lesson back in January and it was ok.  There are obviously some corners that need more work.  Do I remember that the release deadline is in June?  I was hoping the material could be "finished" by then.

**Comment by k8hertweck** [comment]
Yes, the next release is June. I think this timeline works, and would be supportive of adding the lesson to the website in May to gain more visibility, just prior to the June release.

@ntmoore, remember to let us know if you'd like us to solicit someone else to help you out with this lesson!

**Comment by ErinBecker** [comment]
Thanks @ntmoore and @k8hertweck for clarifying. This helps clarify the status of this lesson and will be useful in communicating with instructors and trainees.
