### ISSUE TITLE
Mobile site-menu has poor link color

### ISSUE THREAD

**Issue by sburns** [swcarpentry/website-archive#72]
![](https://www.evernote.com/l/AIQRsBk5cVlJm549JP_6f2EJ1MwJcNYcw_EB/image.png)

This is easy to miss as it only occurs on mobile when the layout switches to the collapsed mode.

**Comment by sburns** [comment]
Meant to add, I think the link color should be white or near-white if we're keeping the blue menu.

**Comment by todrobbins** [comment]
I agree. @gvwilson, I can work on this as well.
