### ISSUE TITLE
Missing jekyll-paginate in config

### ISSUE THREAD

**Issue by todrobbins** [swcarpentry/website-archive#75]
I noticed in the build process the following error:

```
Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
```

Anyone know if this was intentionally left out?

**Comment by gvwilson** [comment]
Is jekyll-paginate installed on GitHub?  If not, we shouldn't use it.

**Comment by andreabedini** [comment]
the right way to make sure we use the same software at github is to depend on their gem. It's explained [here](https://help.github.com/articles/using-jekyll-with-pages/). I'll make a PR.
