### ISSUE TITLE
posts seem too narrow on mobile

### ISSUE THREAD

**Issue by evanwill** [swcarpentry/website-archive#776]
commit f44ba87a19b0a5e98ad089e323d65c8d8b5e4faf a month ago made the blog posts narrower on small screens. I think it's too narrow. I have difficulty reading on iPhone 5 because only about three to four words appear on each line. 

Could we bump it up a bit to `class="small-10 columns"`?

**Comment by jduckles** [comment]
Thanks for the comment @evanwill, I think I fixed it by going to `large-8`. Let me know if it looks better. Note the change will take 15-45min to become live with how we build our website.
