### ISSUE TITLE
Links at Joint future for Software Carpentry and Data Carpentry

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/website-archive#810]
https://software-carpentry.org/blog/2017/09/merger.html has links to Data Carpentry website that could be replaced with links to Software Carpentry website because the content is there as well. For example,

> Over the last few months, a joint group of representatives appointed from (and regularly reporting back to) the governing committees of both organizations has been exploring and moving towards merging the governance and staff organizations to officially recognize this shared alignment and vision, and going forward to best support the community, member organizations, and curriculum.

Could use a link to https://software-carpentry.org/blog/2017/08/mergermotions.html instead of http://www.datacarpentry.org/blog/mergermotions/.

**Comment by weaverbel** [comment]
Since content is easily findable, I am leaving this as is for now.
