### ISSUE TITLE
Logo looks bad on retina display

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#82]
The Software Carpentry logo (a PNG) looks fuzzy on a retina display. We should use an SVG instead, but @gvwilson has so far failed to export a white SVG with a transparent background from Inkscape. cc @jiffyclub (original reporter)

**Comment by todrobbins** [comment]
I can do this if you'd like @gvwilson.

**Comment by gvwilson** [comment]
Yes please!

**Comment by todrobbins** [comment]
@gvwilson see #86 for review

**Comment by gvwilson** [comment]
Fixed by #86 - @jiffyclub can you please test?

**Comment by jiffyclub** [comment]
:+1:
