### ISSUE TITLE
Translate the checklist

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/website-archive#839]
Matthias G. pointed out that the checklists, e.g. 

- https://github.com/swcarpentry/website/blob/gh-pages/pages/checklists_accessibility.html
- https://github.com/swcarpentry/website/blob/gh-pages/pages/checklists_admin.html
- https://github.com/swcarpentry/website/blob/gh-pages/pages/checklists_helper.html
- https://github.com/swcarpentry/website/blob/gh-pages/pages/checklists_host.html
- https://github.com/swcarpentry/website/blob/gh-pages/pages/checklists_instructor.html
- https://github.com/swcarpentry/website/blob/gh-pages/pages/checklists_lead.html
- https://github.com/swcarpentry/website/blob/gh-pages/pages/checklists_learner.html

could be translated to other languages and have a great impact.

https://github.com/fmichonneau/datacarpentry-organization-translations a draft of the French translation.

**Comment by Rekyt** [comment]
@fmichonneau and @maelle had this idea ;)

**Comment by maelle** [comment]
Yep we thought that it might be easier in countries where admin staff will be more at ease using their local language. :-)

**Comment by weaverbel** [comment]
I suggest an update now as this kind of material is now housed in the Carpentries Handbook. Will alert @maneesha that this might need to be opened as an issue against that material rather than the website.

**Comment by weaverbel** [comment]
Assigning to @maneesha for Carpentries handbook inclusion and closing it here.
