### ISSUE TITLE
Improve Blog Post CSS grid

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/website-archive#845]
The width of the blog title element is bigger than the width of the blog content element.

![screenshot from 2017-10-17 15-25-54](https://user-images.githubusercontent.com/1506457/31670726-24b4b7c8-b350-11e7-8e39-ef0a556a7f2b.png)

This creates a strange reading experience when we have very long titles.

Non-blog pages doesn't have this problem, e.g.

![screenshot from 2017-10-17 15-27-31](https://user-images.githubusercontent.com/1506457/31670776-41bb4b0c-b350-11e7-9977-bc544a74088c.png)

My hypothesis is that the empty space on the first screenshot was save for side column, e.g.

![screenshot from 2017-10-17 15-28-58](https://user-images.githubusercontent.com/1506457/31670820-63e4ef1c-b350-11e7-9200-a866ce212b26.png)

I think that doesn't make sense to add the side column to the blog posts. And we can remove the side column from the blog home page without big lost.

# Comments for Pull Request

Changes need to be done at https://github.com/swcarpentry/website/tree/gh-pages/_sass.

**Comment by weaverbel** [comment]
blog now largely on Carpentries site so I am closing this.
