### ISSUE TITLE
Unifying styles

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/website-archive#846]
I thought that this repository was using https://github.com/swcarpentry/styles/ but I noticed that it isn't.
https://github.com/swcarpentry/styles/pull/36 and https://github.com/swcarpentry/styles/pull/37 is related with it but doesn't have many information in the comments.

@gvwilson as you leaded the unifying styles force, do you remember what was the resolution? Thanks in advance.

**Comment by weaverbel** [comment]
Has this been resolved @rgaiacs

**Comment by rgaiacs** [comment]
> Has this been resolved

I'm not completely sure. I'm close this because this will create more troubles than make our life easy.
