### ISSUE TITLE
kramdown vs GitHub Flavored Markdown

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/website-archive#853]
[kramdown](https://kramdown.gettalong.org/) by default is not 100% compatible with [GitHub Flavored Markdown](https://help.github.com/articles/about-writing-and-formatting-on-github/) (GFM). One of the differences is the requirement (kramdown) or not (GFM) that lists **must** have a new line before it start.

# Example

~~~
$ cat sample.md 
foo
- a
- b
- c

bla

- a
- b
- c
~~~

# Kramdow

~~~
$ kramdown sample.md              
<p>foo
- a
- b
- c</p>

<p>bla</p>

<ul>
  <li>a</li>
  <li>b</li>
  <li>c</li>
</ul>
~~~

# GFM

~~~
$ kramdown -i GFM sample.md 
<p>foo</p>
<ul>
  <li>a</li>
  <li>b</li>
  <li>c</li>
</ul>

<p>bla</p>

<ul>
  <li>a</li>
  <li>b</li>
  <li>c</li>
</ul>
~~~

# Implications

Software Carpentry website, using kramdown, and Data Carpentry website, using GFM, convert Markdown files to HTML in different ways. This created many issues in the past, e.g. https://github.com/swcarpentry/website/pull/852, when some blog post need to be cross post in both websites.

`_config.yml` of both sites looks similar but because Software Carpentry host the website in their own server and Data Carpentry uses GitHub's server some kramdown options are different.

~~~
$ grep -C 5 -i kramdown website/_config.yml 
paginate: 10

# Pagination path › Important for blog page in /blog/ to work
paginate_path: "blog/page:num"

# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
kramdown: 
  parse_block_html: true
permalink: /blog/:year/:month/:title.html
highlight: pygments
excerpt_separator: "<!--more-->"
include:
$ grep -C 5 -i kramdown datacarpentry.github.io/_config.yml                    
dc_github_repo_url: "https://github.com/datacarpentry"
dc_github_site_url: "http://datacarpentry.github.io"
dc_website_url: "http://www.datacarpentry.org"


# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:categories/:title/
highlight: pygments
excerpt_separator: "\n\n"
exclude: []
include: ['.htaccess']
~~~

# Recommendation

Apply the following diff

~~~
diff --git a/_config.yml b/_config.yml
index 591e1a81..9376b2fb 100644
--- a/_config.yml
+++ b/_config.yml
@@ -83,6 +83,7 @@ paginate_path: "blog/page:num"
 # Theme works best with Kramdown (using the table of contents function)
 markdown: kramdown
 kramdown: 
+  input: GFM
   parse_block_html: true
 permalink: /blog/:year/:month/:title.html
 highlight: pygments
~~~

so that both websites use the same configuration.

**Comment by weaverbel** [comment]
Now mostly using Carpentries website so I am closing this for now.
