### ISSUE TITLE
Use underscores in person IDs instead of periods

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/website-archive#90]
We currently use dotted names of the form 'surname.forename' (or sometimes 'surname.initial') for user IDs, but this can cause collisions because '.' is a field separator in Ruby (and hence Jekyll). We should switch to using underscores.  (Can't use hyphens because they're part of some people's names.) This will require:
1.  Modifying all user IDs in the AMY database.
2.  Renaming all the PDF certificate files in the 'certification' repo.
3.  Renaming all files in _includes/person in this repository.
4.  Modifying all IDs in _includes/person in this repository.
5.  Modifying all references to those IDs.

**Comment by pbanaszkiewicz** [comment]
@gvwilson do these changes need to be synchronized? Do you want the AMY part to be faster than in v1.3 release (December/January)?

**Comment by gvwilson** [comment]
Nope, this is a long-term thing.

**Comment by pbanaszkiewicz** [comment]
@gvwilson okay. And how is the collision happening?

If "surname.forname" was some variable's value, then you'd use `{{ variable}}` in Liquid and no collision should happen.

**Comment by gvwilson** [comment]
See https://github.com/swcarpentry/website/issues/39 and the comment 
about the dot being eaten.  See also:
-   https://github.com/swcarpentry/website/pull/41
-   https://github.com/swcarpentry/website/issues/10
