### ISSUE TITLE
Navigation bar and open in a new tab

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/website-archive#91]
# Summary

Subtree of navigation bar doesn't disappear after mouse leave.
# Steps to reproduce
1. Select one item on the navigation bar.
2. Open one of the subitem into a new tab.
3. Move the mouse to another item on the navigation bar.
# Result

Both subtree are visible.
# Expected result

Only the subtree of the second item selected is visible.

**Comment by gvwilson** [comment]
Still an issue?

**Comment by gvwilson** [comment]
Is this related to #63? If so, anyone willing to take it on, or should wait wait for the Great Website Redesign?
