### ISSUE TITLE
Width of previous lessons

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/website-archive#92]
At http://software-carpentry.org/lessons/previous/, why not having the tables with the width of the red rectangle on the following screenshot:

![screen shot 2015-12-21 at 07 50 59](https://cloud.githubusercontent.com/assets/1506457/11928043/d2c12640-a7b7-11e5-87a4-d9e32f7ccb62.png)

**Comment by gvwilson** [comment]
Pull request welcome.

On 2015-12-21 9:53 AM, Raniere Silva wrote:

> At http://software-carpentry.org/lessons/previous/, why not having the 
> tables with the width of the red rectangle on the following screenshot:
> 
> screen shot 2015-12-21 at 07 50 59 
> https://cloud.githubusercontent.com/assets/1506457/11928043/d2c12640-a7b7-11e5-87a4-d9e32f7ccb62.png
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/swcarpentry/website/issues/92.

## 

Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org
