### ISSUE TITLE
Mobile layout is broken (on some pages)

### ISSUE THREAD

**Issue by sburns** [swcarpentry/website-archive#93]
![img_0367](https://cloud.githubusercontent.com/assets/440820/11935072/62dd9296-a7cb-11e5-987f-b5656e29583e.jpg)

iPhone 6s, iOS 9.2

**Comment by todrobbins** [comment]
Looks like an `initial-scale`/`device-width` issue. @sburns, is it only happening on that page?

**Comment by sburns** [comment]
Not an exhaustive list. Unfortunately I can't re-produce this in chrome dev tools. Working through the menu and prominent links on the index...
- /scf/index.html is good
- /pages/index.html is good
- /workshops/index.html is bad
- /workshops/request.html is good
- /lessons/index.html is good
- /pages/join.html is bad

**Comment by gvwilson** [comment]
Still an issue?

**Comment by sburns** [comment]
Looks much better!
