### ISSUE TITLE
20 Years of Open Content

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/website-archive#954]
https://opencontent.org/blog/archives/5354 says

> 2018 marks the 20th anniversary of open content

we might want to write a blog post related to it.

**Comment by weaverbel** [comment]
Added to blog wish list

**Comment by rgaiacs** [comment]
@weaverbel Where is the blog wish list?

**Comment by weaverbel** [comment]
I am not sure we have one now - but we do have a blog suggestion link https://docs.google.com/forms/d/e/1FAIpQLSeiu5NzJsLxYueaQrNn_qKbaa5JR2Sz12CeCRyedKQxwb54Dw/viewform
