### ISSUE TITLE
Do we have a staff page?

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/website-archive#965]
Because I couldn't find it.

**Comment by maneesha** [comment]
DC and SWC have their own pages and you're right that the staff parts are not easy to find.  This all needs updating.  I'm guessing this will go in our new joint website.

Data Carpentry:  http://www.datacarpentry.org/people/
Software Carpentry:  https://software-carpentry.org/scf/

**Comment by weaverbel** [comment]
I am creating a staff list for the new Carpentries website @rgaiacs - I am waiting on final word on some staff titles.

**Comment by ErinBecker** [comment]
This is the link to The Carpentries staff page (https://carpentries.org/team/). It should be linked to from this site as well.

**Comment by weaverbel** [comment]
We now have the staff page on The Carpentries so I am closing this.
